### ISSUE TITLE
thread 'leadership1' panicked at 'Expect the event to not close'

### ISSUE THREAD

**Issue by bobdobs** [input-output-hk/jormungandr#1009]
**Describe the bug**
v0.6.5 error when shutting down using jcli 

**Mandatory Information**
1. jcli 0.6.5 (HEAD-052f7be, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
2. jormungandr 0.6.5 (HEAD-052f7be, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**
1. Start jormungandr: 'export RUST_BACKTRACE=full && jormungandr --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --config config.yaml'
2. Shut down with jcli: 'jcli rest v0 shutdown get --host "http://127.0.0.1:8443/api"'
3. Error: 'thread 'leadership1' panicked at 'Expect the event to not close', src/libcore/option.rs:1166:5'

**Expected behavior**
jormungandr was running normally as far as I could see so did not expect an error when shutting down using jcli

**Additional context**
```
Backtrace: 
thread 'leadership1' panicked at 'Expect the event to not close', src/libcore/option.rs:1166:5
stack backtrace:
   0:     0x5608f68bc518 - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x5608f68bc518 - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x5608f68bc518 - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5608f68bc518 - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5608f68bc518 - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x5608f68bbc67 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x5608f68bbc67 - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x5608f68bb78f - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x5608f68ca5a6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5608f68d556c - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x5608f68db716 - core::option::expect_failed::h292a6217b603c24f
                               at src/libcore/option.rs:1166
  11:     0x5608f6c5c532 - futures::future::chain::Chain<A,B,C>::poll::h449f04ad592a465c
  12:     0x5608f6c8c3b6 - <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll::h8ddbcbcf27d906eb
  13:     0x5608f694ecf0 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::hce6ccccc47259112
  14:     0x5608f68b0eae - futures::task_impl::std::set::hc5af9ca7fb3d8e18
  15:     0x5608f68acc69 - tokio_threadpool::worker::Worker::run_task::hb9adf17aea724148
  16:     0x5608f68aafb0 - tokio_threadpool::worker::Worker::run::h1de540ce50609a82
  17:     0x5608f68931fa - std::thread::local::LocalKey<T>::with::hf99a5b5fb783d300
  18:     0x5608f68946e5 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::hf0017246924db371
  19:     0x5608f68a926f - std::sys_common::backtrace::__rust_begin_short_backtrace::h4c7a5861bb9e17ad
  20:     0x5608f68aa671 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h87c80692d3694042
  21:     0x5608f68ca0af - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2877b2aefb0fd627
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  22:     0x5608f68cb54c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13f473dbcdaa0fef
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  23:     0x5608f68cb54c - std::sys_common::thread::start_thread::h562a7c4953cb1d31
                               at src/libstd/sys_common/thread.rs:13
  24:     0x5608f68cb54c - std::sys::unix::thread::Thread::new::thread_start::h382c6ae14181d163
                               at src/libstd/sys/unix/thread.rs:79
  25:     0x7f6ab329f6ba - start_thread
  26:     0x7f6ab2dbd41d - clone
  27:                0x0 - <unknown>
Expect the event to not close

```

**Comment by NicolasDP** [comment]
Thanks for the report. I will still put it in low priority as this is not a problem for the safety of the nodes or your data. However this is something we will work on once the most pressing issues are sorted.
