### ISSUE TITLE
on 0.7.0-alpha.dev: cannot start from block 0 hash

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#1011]
needs to investigate but the steps to reproduce it is:

1. use self node scripts: `./bootstrap -p 8080 -g -s 3 -e 100 -o`
2. starts the node with the `block0`: `jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml`, wait a couple of seconds and then stop it
3. starts the node with the `block0 hash`: `jormungandr --genesis-block-hash $(cat ./block-0.bin | jcli genesis hash) --config ./config.yaml --secret ./pool-secret1.yaml`

Once the leadership node is awake to prepare a new block, every new created blocks are invalid:

```
thread 'block0' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("cannot process leadership block"), State { next_error: Some(Error(BlockHeaderVerificationFailed("Block proof is invalid"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
called `Result::unwrap()` on an `Err` value: Error(Msg("cannot process leadership block"), State { next_error: Some(Error(BlockHeaderVerificationFailed("Block proof is invalid"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })
```

**Comment by dmitrystas** [comment]
the same error on rc4

```
Nov 04 23:53:04.001 INFO leader event starting, date: 128.134, leader: 1, task: leadership
thread 'block0' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("cannot process leadership block"), State { next_error: Some(Error(BlockHeaderVerificationFailed("Block proof is invalid"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: error_chain::backtrace::imp::InternalBacktrace::new
   1: jormungandr::blockchain::chain::Blockchain::post_check_header
   2: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   3: futures::task_impl::Spawn<T>::poll_future_notify
   4: jormungandr::blockchain::process::run_handle_input
   5: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
   6: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   7: futures::task_impl::std::set
   8: tokio_threadpool::worker::Worker::run_task
   9: tokio_threadpool::worker::Worker::run
  10: std::thread::local::LocalKey<T>::with
  11: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  16: start_thread
  17: clone
) } })), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0: error_chain::backtrace::imp::InternalBacktrace::new
   1: jormungandr::blockchain::chain::Blockchain::post_check_header
   2: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   3: futures::task_impl::Spawn<T>::poll_future_notify
   4: jormungandr::blockchain::process::run_handle_input
   5: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
   6: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
   7: futures::task_impl::std::set
   8: tokio_threadpool::worker::Worker::run_task
   9: tokio_threadpool::worker::Worker::run
  10: std::thread::local::LocalKey<T>::with
  11: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  16: start_thread
  17: clone
) } })', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x5576a4f2f068 - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x5576a4f2f068 - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x5576a4f2f068 - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5576a4f2f068 - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5576a4f2f068 - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x5576a4f2e7b7 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x5576a4f2e7b7 - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x5576a4f2e2df - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x5576a4f3d506 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5576a4f484cc - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x5576a4f4e716 - core::result::unwrap_failed::hf7591c1dd9412006
                               at src/libcore/result.rs:1084
  11:     0x5576a5381469 - jormungandr::blockchain::process::run_handle_input::h7f9b4831a73f616c
  12:     0x5576a51900d1 - <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::hd697990e0929895b
  13:     0x5576a5158c0b - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h32d9e0b4088135c6
  14:     0x5576a4f238a0 - futures::task_impl::std::set::h0cacc9ee8c9154d6
  15:     0x5576a4f1f5c9 - tokio_threadpool::worker::Worker::run_task::hf705a63441041281
  16:     0x5576a4f1d900 - tokio_threadpool::worker::Worker::run::h03f194a2e37bf27f
  17:     0x5576a4f0559a - std::thread::local::LocalKey<T>::with::h06ee71bf920c7894
  18:     0x5576a4f06b35 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h53d5f0595e00f269
  19:     0x5576a4f1bbaf - std::sys_common::backtrace::__rust_begin_short_backtrace::h063f1c4740e5d66f
  20:     0x5576a4f1cfc1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hee805df2580efb81
  21:     0x5576a4f3ca0f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2877b2aefb0fd627
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  22:     0x5576a4f3e4ac - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13f473dbcdaa0fef
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  23:     0x5576a4f3e4ac - std::sys_common::thread::start_thread::h562a7c4953cb1d31
                               at src/libstd/sys_common/thread.rs:13
  24:     0x5576a4f3e4ac - std::sys::unix::thread::Thread::new::thread_start::h382c6ae14181d163
                               at src/libstd/sys/unix/thread.rs:79
  25:     0x7f6ce04b8fa3 - start_thread
  26:     0x7f6ce03cf4cf - clone
  27:                0x0 - <unknown>
thread 'leadership0' panicked at 'Expect the event to not close', src/libcore/option.rs:1166:5
stack backtrace:
   0:     0x5576a4f2f068 - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x5576a4f2f068 - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x5576a4f2f068 - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5576a4f2f068 - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5576a4f2f068 - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x5576a4f2e7b7 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x5576a4f2e7b7 - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x5576a4f2e2df - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x5576a4f3d506 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5576a4f484cc - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x5576a4f4e676 - core::option::expect_failed::h292a6217b603c24f
                               at src/libcore/option.rs:1166
  11:     0x5576a52e7381 - futures::future::chain::Chain<A,B,C>::poll::hcaaa7f312e7910df
  12:     0x5576a5303626 - <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll::hd93956133b25be2f
  13:     0x5576a516c9d0 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::hecb4577ad96de8b2
  14:     0x5576a4f238a0 - futures::task_impl::std::set::h0cacc9ee8c9154d6
  15:     0x5576a4f1f5c9 - tokio_threadpool::worker::Worker::run_task::hf705a63441041281
  16:     0x5576a4f1d900 - tokio_threadpool::worker::Worker::run::h03f194a2e37bf27f
  17:     0x5576a4f0559a - std::thread::local::LocalKey<T>::with::h06ee71bf920c7894
  18:     0x5576a4f06b35 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h53d5f0595e00f269
  19:     0x5576a4f1bbaf - std::sys_common::backtrace::__rust_begin_short_backtrace::h063f1c4740e5d66f
  20:     0x5576a4f1cfc1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hee805df2580efb81
  21:     0x5576a4f3ca0f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2877b2aefb0fd627
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  22:     0x5576a4f3e4ac - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13f473dbcdaa0fef
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  23:     0x5576a4f3e4ac - std::sys_common::thread::start_thread::h562a7c4953cb1d31
                               at src/libstd/sys_common/thread.rs:13
  24:     0x5576a4f3e4ac - std::sys::unix::thread::Thread::new::thread_start::h382c6ae14181d163
                               at src/libstd/sys/unix/thread.rs:79
  25:     0x7f6ce04b8fa3 - start_thread
  26:     0x7f6ce03cf4cf - clone
  27:                0x0 - <unknown>
Expect the event to not close
```
