### ISSUE TITLE
thread 'network1' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/jormungandr#1086]
**Describe the bug**
Looks like Jormungandr does not check stored blocks in SQlite if they belong to same genesis as the currently running instance. When remote peer is served a block from old chain following is logged, 
```
Nov 07 22:25:00.399 INFO incoming connection on 82.209.54.76:3102, peer_addr: 185.161.193.61:48070, task: network
thread 'network1' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5
```
occurs, more context below
```
Nov 07 22:24:38.184 INFO received block announcement, hash: 402b1d9cbec010493b4cdbdf36357c54dcfe5e918fc9cc09b28682de5b60d73d, node_id: ab1cd3c94161ab06c058697a19095a6ed91d85688a2b7a21, peer_addr: 139.99.221.149:4004, task: network
Nov 07 22:24:58.164 INFO received block announcement, hash: f852153743616bb3bb1503705083327d6bf65e61a5e4d4555085f962bf0e903d, node_id: ab1cd3c94161ab06c058697a19095a6ed91d85688a2b7a21, peer_addr: 139.99.221.149:4004, task: network
Nov 07 22:24:59.750 INFO incoming connection on 82.209.54.76:3102, peer_addr: 185.161.193.61:48066, task: network
thread 'network1' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5
Nov 07 22:24:59.785 INFO incoming connection closed, peer_addr: 185.161.193.61:48066, task: network
Nov 07 22:25:00.399 INFO incoming connection on 82.209.54.76:3102, peer_addr: 185.161.193.61:48070, task: network
thread 'network1' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5
Nov 07 22:25:00.446 INFO incoming connection closed, peer_addr: 185.161.193.61:48070, task: network
Nov 07 22:25:02.470 INFO incoming connection on 82.209.54.76:3102, peer_addr: 185.161.193.61:48074, task: network
Nov 07 22:25:08.168 INFO received block announcement, hash: 0f6aef4f58accc1853bb51f6634fd67b77fb8b6d2c16da034b07446d17964c5f, node_id: ab1cd3c94161ab06c058697a19095a6ed91d85688a2b7a21, peer_addr: 139.99.221.149:4004, task: network
```

**Mandatory Information**
1. `jcli --full-version` output;

```
[mark_stopka@docker-host-01 jormungandr]$ ./jcli --full-version
jcli 0.7.0-rc5 (HEAD-d4ac194, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
[mark_stopka@docker-host-01 jormungandr]$
```

2. `jormungandr --full-version` output;

```
[mark_stopka@docker-host-01 jormungandr]$ ./jormungandr --full-version
jormungandr 0.7.0-rc5 (HEAD-d4ac194, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
[mark_stopka@docker-host-01 jormungandr]$
```

**To Reproduce**
Unable to reproduce with SQlite storage from a Private Nightly Testnet being used on a IOHK operated nightly testnet.

**Expected behavior**
Jormungandr should check existing blocks in the SQlite database against provided genesis hash and exit with an error when not during bootstrap.

**Additional context**

**Comment by mark-stopka** [comment]
Unable to reproduce with RC5 on an IOHK testnet, attaching debug log anyway...

[issue-1086.log](https://github.com/input-output-hk/jormungandr/files/3824184/issue-1086.log)
