### ISSUE TITLE
Panic in jormungandr 0.7.0-rc7

### ISSUE THREAD

**Issue by stakeada** [input-output-hk/jormungandr#1105]
**Describe the bug**
I've run the new version of jormungandr and it panicks.

**Mandatory Information**
1. 

```
jcli 0.7.0-rc7 (HEAD-cf5fcaea, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
```
2. 

```
jormungandr 0.7.0-rc7 (HEAD-cf5fcaea, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
```

**To Reproduce**

Just run the cardano node with:
```
/srv/jormungandr/target/release/jormungandr --config config.yaml --genesis-block-hash cfd99bc54ebf44b44e72db7e2d48a40499888781e7628ea0fbf286bfd480ca58 --secret node_config.yaml 
```

Error:
```
Nov 10 17:58:57.572 INFO Starting jormungandr 0.7.0-rc7 (HEAD-cf5fcaea, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Nov 10 17:58:57.573 INFO storing blockchain in '"/srv/storage/blocks.sqlite"', task: init

Nov 10 17:59:12.590 INFO connecting to bootstrap peer 18.196.168.220:3000, peer_addr: 18.196.168.220:3000, task: bootstrap
Nov 10 17:59:12.691 INFO update current branch tip, peer_addr: 18.196.168.220:3000, task: bootstrap
Nov 10 17:59:12.749 INFO initial bootstrap completed, peer_addr: 18.196.168.220:3000, task: bootstrap
Nov 10 17:59:12.750 INFO starting task, task: client-query
Nov 10 17:59:12.750 INFO start listening and accepting gRPC connections on 0.0.0.0:3100, task: network
Nov 10 17:59:12.750 ERRO failed to listen for P2P connections at 0.0.0.0:3100, reason: failed to listen for connections on 0.0.0.0:3100, task: network
Nov 10 17:59:12.751 INFO connecting to peer, node_id: 431214988b71f3da55a342977fea1f3d8cba460d031a839c, peer_addr: 3.124.132.123:3000, task: network
Nov 10 17:59:12.751 INFO connecting to peer, node_id: e9cf7b29019e30d01a658abd32403db85269fe907819949d, peer_addr: 18.184.181.30:3000, task: network
Nov 10 17:59:12.751 INFO connecting to peer, node_id: acaba9c8c4d8ca68ac8bad5fe9bd3a1ae8de13816f40697c, peer_addr: 184.169.162.15:3000, task: network
Nov 10 17:59:12.751 INFO connecting to peer, node_id: bcfc82c9660e28d4dcb4d1c8a390350b18d04496c2ac8474, peer_addr: 13.56.87.134:3000, task: network
Nov 10 17:59:12.751 INFO connecting to peer, node_id: c32e4e7b9e6541ce124a4bd7a990753df4183ed65ac59e34, peer_addr: 13.230.48.191:3000, task: network
Nov 10 17:59:12.751 INFO connecting to peer, node_id: e4fda5a674f0838b64cacf6d22bbae38594d7903aba2226f, peer_addr: 13.230.137.72:3000, task: network
Nov 10 17:59:12.751 INFO connecting to peer, node_id: 74a9949645cdb06d0358da127e897cbb0a7b92a1d9db8e70, peer_addr:thread ' network018' panicked at '.Box<Any>196', .jormungandr/src/main.rs168:.233220::303000
, stack backtrace:
task: network
   0:     0x557641f9c78b - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x557641f9c78b - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x557641f9c78b - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x557641f9c78b - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x557641f9c78b - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x557641f9c466 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x557641f9cefd - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x55764164eddd - std::panicking::begin_panic::hdc61dc718a038cc4
   8:     0x55764189cdbd - jormungandr::start_services::{{closure}}::{{closure}}::hc8e0bb06b81489a6
   9:     0x55764164f082 - std::panicking::try::do_call::h664e2e22ab9d4677
  10:     0x557641fa0eda - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  11:     0x55764187d23e - <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::h1b0a72d49582b3d2
  12:     0x557641872425 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h019fceee3ebaac9e
  13:     0x557641f78492 - futures::task_impl::std::set::h4da57ab4e7fef3bd
  14:     0x557641f780d2 - std::panicking::try::do_call::h305167b7e1d70d16
  15:     0x557641fa0eda - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  16:     0x557641f77cf9 - tokio_threadpool::task::Task::run::hce32068ac13f5307
  17:     0x557641f72966 - tokio_threadpool::worker::Worker::run_task::hec499a10ccce2ea1
  18:     0x557641f71e00 - tokio_threadpool::worker::Worker::run::h5a94d141c00a343d
  19:     0x557641f52a30 - std::thread::local::LocalKey<T>::with::h481d319fd660de64
  20:     0x557641f52d18 - std::thread::local::LocalKey<T>::with::hf122994f0d80fe95
  21:     0x557641f52baf - std::thread::local::LocalKey<T>::with::h550bec577dc98060
  22:     0x557641f5607e - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h1a69c100ecb22c57
  23:     0x557641f7522a - std::thread::local::LocalKey<T>::with::h7cb6a9ae21867f59
  24:     0x557641f75019 - std::thread::local::LocalKey<T>::with::h3b813fc02b707021
  25:     0x557641f7a608 - std::sys_common::backtrace::__rust_begin_short_backtrace::h53705cc32ea6361d
  26:     0x557641f7811c - std::panicking::try::do_call::he8f7859245a83e3b
  27:     0x557641fa0eda - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  28:     0x557641f701a0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hce86251bb7dcb620
  29:     0x557641f8d70f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2877b2aefb0fd627
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  30:     0x557641fa0220 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13f473dbcdaa0fef
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  31:     0x557641fa0220 - std::sys_common::thread::start_thread::h562a7c4953cb1d31
                               at src/libstd/sys_common/thread.rs:13
  32:     0x557641fa0220 - std::sys::unix::thread::Thread::new::thread_start::h382c6ae14181d163
                               at src/libstd/sys/unix/thread.rs:79
  33:     0x7fa70ec10ef7 - start_thread
  34:     0x7fa70e92e22f - __GI___clone
  35:                0x0 - <unknown>
```

**Expected behavior**
A node should start without issues.

**Comment by mmahut** [comment]
```ERRO failed to listen for P2P connections at 0.0.0.0:3100```

Do you have permission to bind on this interface and/or the port?

**Comment by stakeada** [comment]
Yes, running this in nix-shell as root.

**Comment by NicolasDP** [comment]
it looks like you cannot listen on that address. try another port number or check that the port number is not already in use.
