### ISSUE TITLE
0.7.0 Block proof is invalid

### ISSUE THREAD

**Issue by dmitrystas** [input-output-hk/jormungandr#1128]
> Nov 14 07:57:49.002 INFO Leader event started, event_remaining_time: 4s 997ms 703us 611ns, event_end: 2019-11-14T06:57:54+00:00, event_start: 2019-11-14T06:57:49+00:00, event_date: 68.207, leader_id: 1, task: leadership
> thread 'block0' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("cannot process leadership block"), State { next_error: Some(Error(BlockHeaderVerificationFailed("Block proof is invalid"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
>    0: error_chain::backtrace::imp::InternalBacktrace::new
>    1: jormungandr::blockchain::chain::Blockchain::post_check_header
>    2: <futures::future::map::Map<A,F> as futures::future::Future>::poll
>    3: futures::task_impl::Spawn<T>::poll_future_notify
>    4: std::thread::local::LocalKey<T>::with
>    5: jormungandr::blockchain::process::run_handle_input
>    6: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
>    7: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
>    8: futures::task_impl::std::set
>    9: tokio_threadpool::worker::Worker::run_task
>   10: tokio_threadpool::worker::Worker::run
>   11: std::thread::local::LocalKey<T>::with
>   12: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
>   13: std::sys_common::backtrace::__rust_begin_short_backtrace
>   14: core::ops::function::FnOnce::call_once{{vtable.shim}}
>   15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
>   16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
>       std::sys_common::thread::start_thread
>              at src/libstd/sys_common/thread.rs:13
>       std::sys::unix::thread::Thread::new::thread_start
>              at src/libstd/sys/unix/thread.rs:79
>   17: start_thread
>   18: clone
> ) } })), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
>    0: error_chain::backtrace::imp::InternalBacktrace::new
>    1: jormungandr::blockchain::chain::Blockchain::post_check_header
>    2: <futures::future::map::Map<A,F> as futures::future::Future>::poll
>    3: futures::task_impl::Spawn<T>::poll_future_notify
>    4: std::thread::local::LocalKey<T>::with
>    5: jormungandr::blockchain::process::run_handle_input
>    6: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
>    7: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
>    8: futures::task_impl::std::set
>    9: tokio_threadpool::worker::Worker::run_task
>   10: tokio_threadpool::worker::Worker::run
>   11: std::thread::local::LocalKey<T>::with
>   12: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
>   13: std::sys_common::backtrace::__rust_begin_short_backtrace
>   14: core::ops::function::FnOnce::call_once{{vtable.shim}}
>   15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
>   16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
>       std::sys_common::thread::start_thread
>              at src/libstd/sys_common/thread.rs:13
>       std::sys::unix::thread::Thread::new::thread_start
>              at src/libstd/sys/unix/thread.rs:79
>   17: start_thread
>   18: clone
> ) } })', src/libcore/result.rs:1165:5
> stack backtrace:
>    0:     0x55b42db8a49c - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
>                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
>    1:     0x55b42db8a49c - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
>                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
>    2:     0x55b42db8a49c - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
>                                at src/libstd/sys_common/backtrace.rs:76
>    3:     0x55b42db8a49c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
>                                at src/libstd/sys_common/backtrace.rs:60
>    4:     0x55b42d5a1aec - core::fmt::write::h01edf6dd68a42c9c
>                                at src/libcore/fmt/mod.rs:1030
>    5:     0x55b42db89cb6 - std::io::Write::write_fmt::hf15985f193f03c04
>                                at src/libstd/io/mod.rs:1412
>    6:     0x55b42db89930 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
>                                at src/libstd/sys_common/backtrace.rs:64
>    7:     0x55b42db89930 - std::sys_common::backtrace::print::hf89a79e3921a2366
>                                at src/libstd/sys_common/backtrace.rs:49
>    8:     0x55b42db89930 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
>                                at src/libstd/panicking.rs:196
>    9:     0x55b42db8907f - std::panicking::default_hook::h8f803b0bc31a5c37
>                                at src/libstd/panicking.rs:210
>   10:     0x55b42db8907f - std::panicking::rust_panic_with_hook::h825f041245da8739
>                                at src/libstd/panicking.rs:473
>   11:     0x55b42db88baf - std::panicking::continue_panic_fmt::hbe0378e33481e81b
>                                at src/libstd/panicking.rs:380
>   12:     0x55b42db97696 - rust_begin_unwind
>                                at src/libstd/panicking.rs:307
>   13:     0x55b42d59bd69 - core::panicking::panic_fmt::h527855ce0bc891f6
>                                at src/libcore/panicking.rs:85
>   14:     0x55b42d5a2156 - core::result::unwrap_failed::ha8b77e6004f0ba38
>                                at src/libcore/result.rs:1165
>   15:     0x55b42d7ed813 - jormungandr::blockchain::process::run_handle_input::ha54d9077acaf54a0
>   16:     0x55b42d712482 - <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::hedff1ccada1b749d
>   17:     0x55b42d41f003 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h71e7e754edbd6137
>   18:     0x55b42dbdc410 - futures::task_impl::std::set::h85cd6d577f63ac1a
>   19:     0x55b42dbd825c - tokio_threadpool::worker::Worker::run_task::h63ebf3f2b2c9c06d
>   20:     0x55b42dbd64e0 - tokio_threadpool::worker::Worker::run::hf4c7ef5a6eee7453
>   21:     0x55b42dbbac10 - std::thread::local::LocalKey<T>::with::h5d2e8df7c537e6f0
>   22:     0x55b42dbbc16c - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h89ce5b4bd9e42aaa
>   23:     0x55b42dbd473b - std::sys_common::backtrace::__rust_begin_short_backtrace::he976dcc67a40945d
>   24:     0x55b42dbd5c58 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he2d293759f141fc7
>   25:     0x55b42db96f3f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h483711add4ba2330
>                                at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
>   26:     0x55b42db9873c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7605b45eb29ed0be
>                                at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
>   27:     0x55b42db9873c - std::sys_common::thread::start_thread::h557b0c2dc4449562
>                                at src/libstd/sys_common/thread.rs:13
>   28:     0x55b42db9873c - std::sys::unix::thread::Thread::new::thread_start::h7c2a7f9b68fe4bba
>                                at src/libstd/sys/unix/thread.rs:79
>   29:     0x7fce9eaddfa3 - start_thread
>   30:     0x7fce9e9f44cf - clone
>   31:                0x0 - <unknown>
> Nov 14 07:57:49.134 WARN response canceled by the processing task, node_id: 641aeac4159fa79ddb74f84ffad94a0ab48ae3763d9aa550, peer_addr: 110.143.155.171:9330, task: network
> Nov 14 07:57:49.134 WARN pulled block validation failed: Error { code: Unavailable, source: Error { code: Unavailable, cause: Canceled } }, node_id: 641aeac4159fa79ddb74f84ffad94a0ab48ae3763d9aa550, peer_addr: 110.143.155.171:9330, task: network
> Nov 14 07:57:49.134 WARN response canceled by the processing task, node_id: 641aeac4159fa79ddb74f84ffad94a0ab48ae3763d9aa550, peer_addr: 110.143.155.171:9330, task: network
> Nov 14 07:57:49.135 WARN pulled block validation failed: Error { code: Unavailable, source: Error { code: Unavailable, cause: Canceled } }, node_id: 641aeac4159fa79ddb74f84ffad94a0ab48ae3763d9aa550, peer_addr: 110.143.155.171:9330, task: network
> called `Result::unwrap()` on an `Err` value: Error(Msg("cannot process leadership block"), State { next_error: Some(Error(BlockHeaderVerificationFailed("Block proof is invalid"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
>    0: error_chain::backtrace::imp::InternalBacktrace::new
>    1: jormungandr::blockchain::chain::Blockchain::post_check_header
>    2: <futures::future::map::Map<A,F> as futures::future::Future>::poll
>    3: futures::task_impl::Spawn<T>::poll_future_notify
>    4: std::thread::local::LocalKey<T>::with
>    5: jormungandr::blockchain::process::run_handle_input
>    6: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
>    7: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
>    8: futures::task_impl::std::set
>    9: tokio_threadpool::worker::Worker::run_task
>   10: tokio_threadpool::worker::Worker::run
>   11: std::thread::local::LocalKey<T>::with
>   12: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
>   13: std::sys_common::backtrace::__rust_begin_short_backtrace
>   14: core::ops::function::FnOnce::call_once{{vtable.shim}}
>   15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
>   16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
>       std::sys_common::thread::start_thread
>              at src/libstd/sys_common/thread.rs:13
>       std::sys::unix::thread::Thread::new::thread_start
>              at src/libstd/sys/unix/thread.rs:79
>   17: start_thread
>   18: clone
> ) } })), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
>    0: error_chain::backtrace::imp::InternalBacktrace::new
>    1: jormungandr::blockchain::chain::Blockchain::post_check_header
>    2: <futures::future::map::Map<A,F> as futures::future::Future>::poll
>    3: futures::task_impl::Spawn<T>::poll_future_notify
>    4: std::thread::local::LocalKey<T>::with
>    5: jormungandr::blockchain::process::run_handle_input
>    6: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
>    7: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
>    8: futures::task_impl::std::set
>    9: tokio_threadpool::worker::Worker::run_task
>   10: tokio_threadpool::worker::Worker::run
>   11: std::thread::local::LocalKey<T>::with
>   12: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
>   13: std::sys_common::backtrace::__rust_begin_short_backtrace
>   14: core::ops::function::FnOnce::call_once{{vtable.shim}}
>   15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
>   16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
>       std::sys_common::thread::start_thread
>              at src/libstd/sys_common/thread.rs:13
>       std::sys::unix::thread::Thread::new::thread_start
>              at src/libstd/sys/unix/thread.rs:79
>   17: start_thread
>   18: clone
> ) } })

**Comment by NicolasDP** [comment]
can we see the full version `--full-version` ?
what network were you connected to?

**Comment by dmitrystas** [comment]
> can we see the full version `--full-version` ?

jormungandr 0.7.0 (HEAD-a93d4f6, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

> what network were you connected to?

Cardano Private Testnet
