### ISSUE TITLE
0.7.1 appears to have a memory leak

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/jormungandr#1187]
**Describe the bug**
Jormungandr 0.7.1 climbs to over 11 GB RAM and crashes

**Mandatory Information**
1. jcli 0.7.1 (HEAD-c57466d5, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.7.1 (HEAD-c57466d5, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
1. Run Jormungandr 0.7.1 for 8 to 10 hours
2. I was also running a looping script from master scripts, send-money.sh, that sends 2 tx every 20 seconds (which appears unaffected)

**Expected behavior**
Not Crashing

**Additional context**
Mac OSX 10.15.1

Nov 22 22:47:45.668 INFO incoming HTTP/2 connection error, reason: connection error: Operation timed out (os error 60), peer_addr: 2.56.214.85:44394, task: network
Nov 22 22:47:45.668 ERRO Error while accepting connection on 192.168.1.116:3100: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, task: network
thread 'network17' panicked at 'Box<Any>', jormungandr/src/main.rs:240:30
stack backtrace:
   0:        0x1070e1e95 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h66f38d4abb2e41c1
   1:        0x1071044d0 - core::fmt::write::h4f487e714088986d
   2:        0x1070dc55b - std::io::Write::write_fmt::h7bd7b6fe8b47c5fb
   3:        0x1070e419a - std::panicking::default_hook::{{closure}}::heee79636c241547c
   4:        0x1070e3ea5 - std::panicking::default_hook::hfcbd07059d15441e
   5:        0x1070e4867 - std::panicking::rust_panic_with_hook::h0c4b67125f55410a
   6:        0x10710a551 - std::panicking::begin_panic::h817647a7cd322460
   7:        0x1067419b0 - jormungandr::start_services::{{closure}}::{{closure}}::hbe6ccf2504f41799
   8:        0x106802e92 - std::panicking::try::do_call::h14fc7badb6d62f7a
   9:        0x1070e810f - __rust_maybe_catch_panic
  10:        0x106842472 - <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::h46dac3a96d1bb17b
  11:        0x10671bcd2 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h25b5e4709dcfb12e
  12:        0x1069b309b - futures::future::chain::Chain<A,B,C>::poll::h22b10e87d8543eeb
  13:        0x1070c2c4d - futures::task_impl::std::set::hf6a81d7ad603e678
  14:        0x1070c27e6 - std::panicking::try::do_call::hcd8daf8285f047e0
  15:        0x1070e810f - __rust_maybe_catch_panic
  16:        0x1070c224c - tokio_threadpool::task::Task::run::h760436a59674e20c
  17:        0x1070bcfe2 - tokio_threadpool::worker::Worker::run_task::ha7990cca7b384af0
  18:        0x1070bc650 - tokio_threadpool::worker::Worker::run::hcce58b75f670a94e
  19:        0x1070a015d - std::thread::local::LocalKey<T>::with::h10e97151fce0e682
  20:        0x1070a0423 - std::thread::local::LocalKey<T>::with::h8bd1893f4e1dcef8
  21:        0x1070a02d5 - std::thread::local::LocalKey<T>::with::h25cef123f17cae5c
  22:        0x1070a1f21 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h936dd1a535065305
  23:        0x1070bfcdb - std::thread::local::LocalKey<T>::with::h4ea373a2c47f8794
  24:        0x1070bf78b - std::thread::local::LocalKey<T>::with::h144e317d6ab1920c
  25:        0x1070b8f60 - std::sys_common::backtrace::__rust_begin_short_backtrace::h75b0980a2f3dd595
  26:        0x1070c2750 - std::panicking::try::do_call::h2b96ac45e1874e98
  27:        0x1070e810f - __rust_maybe_catch_panic
  28:        0x1070ba8b7 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he746ca0ef6339ffd
  29:        0x1070d585e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd1afe4d791e3679f
  30:        0x1070e762e - std::sys::unix::thread::Thread::new::thread_start::h785fcf8d81bd0f52
  31:     0x7fff6b26cd36 - _pthread_start
Nov 22 22:47:45.791 CRIT Task panicked, task: network
Nov 22 22:47:45.791 INFO Shutting down node
Nov 22 22:47:45.802 WARN Shutting down service client-query (up since 9h 54m 54s 314ms 677us 39ns): receiving on a closed channel, task: client-query

--- Another backtrace ----

Nov 23 06:16:04.851 INFO connecting to peer, node_id: 6d424f90524a8a421f8c488d3cb024f7aebd6ce4ed174a79, peer_addr: 18.217.59.250:3100, task: network
Nov 23 06:16:04.884 INFO failed to connect to peer, reason: Connection refused (os error 61), node_id: 6d424f90524a8a421f8c488d3cb024f7aebd6ce4ed174a79, peer_addr: 18.217.59.250:3100, task: network
Nov 23 06:16:05.851 INFO incoming HTTP/2 connection error, reason: connection error: Operation timed out (os error 60), peer_addr: 3.124.132.123:45924, task: network
Nov 23 06:16:05.851 ERRO Error while accepting connection on 192.168.1.116:3100: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, task: network
thread 'network3' panicked at 'Box<Any>', jormungandr/src/main.rs:240:30
stack backtrace:
   0:        0x10114ae95 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h66f38d4abb2e41c1
   1:        0x10116d4d0 - core::fmt::write::h4f487e714088986d
   2:        0x10114555b - std::io::Write::write_fmt::h7bd7b6fe8b47c5fb
   3:        0x10114d19a - std::panicking::default_hook::{{closure}}::heee79636c241547c
   4:        0x10114cea5 - std::panicking::default_hook::hfcbd07059d15441e
   5:        0x10114d867 - std::panicking::rust_panic_with_hook::h0c4b67125f55410a
   6:        0x101173551 - std::panicking::begin_panic::h817647a7cd322460
   7:        0x1007aa9b0 - jormungandr::start_services::{{closure}}::{{closure}}::hbe6ccf2504f41799
   8:        0x10086be92 - std::panicking::try::do_call::h14fc7badb6d62f7a
   9:        0x10115110f - __rust_maybe_catch_panic
  10:        0x1008ab472 - <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::h46dac3a96d1bb17b
  11:        0x100784cd2 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h25b5e4709dcfb12e
  12:        0x100a1c09b - futures::future::chain::Chain<A,B,C>::poll::h22b10e87d8543eeb
  13:        0x10112bc4d - futures::task_impl::std::set::hf6a81d7ad603e678
  14:        0x10112b7e6 - std::panicking::try::do_call::hcd8daf8285f047e0
  15:        0x10115110f - __rust_maybe_catch_panic
  16:        0x10112b24c - tokio_threadpool::task::Task::run::h760436a59674e20c
  17:        0x101125fe2 - tokio_threadpool::worker::Worker::run_task::ha7990cca7b384af0
  18:        0x101125650 - tokio_threadpool::worker::Worker::run::hcce58b75f670a94e
  19:        0x10110915d - std::thread::local::LocalKey<T>::with::h10e97151fce0e682
  20:        0x101109423 - std::thread::local::LocalKey<T>::with::h8bd1893f4e1dcef8
  21:        0x1011092d5 - std::thread::local::LocalKey<T>::with::h25cef123f17cae5c
  22:        0x10110af21 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h936dd1a535065305
  23:        0x101128cdb - std::thread::local::LocalKey<T>::with::h4ea373a2c47f8794
  24:        0x10112878b - std::thread::local::LocalKey<T>::with::h144e317d6ab1920c
  25:        0x101121f60 - std::sys_common::backtrace::__rust_begin_short_backtrace::h75b0980a2f3dd595
  26:        0x10112b750 - std::panicking::try::do_call::h2b96ac45e1874e98
  27:        0x10115110f - __rust_maybe_catch_panic
  28:        0x1011238b7 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he746ca0ef6339ffd
  29:        0x10113e85e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd1afe4d791e3679f
  30:        0x10115062e - std::sys::unix::thread::Thread::new::thread_start::h785fcf8d81bd0f52
  31:     0x7fff6b26cd36 - _pthread_start
Nov 23 06:16:05.960 CRIT Task panicked, task: network
Nov 23 06:16:05.960 INFO Shutting down node
Nov 23 06:16:15.700 WARN Shutting down service client-query (up since 7h 10m 30s 854ms 974us 218ns): receiving on a closed channel, task: client-query

**Comment by rickymac68** [comment]
It just crashed again after 38 minutes.

Nov 23 09:30:22.197 ERRO Error while accepting connection on 192.168.1.116:3100: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, task: network
thread 'network6' panicked at 'Box<Any>', jormungandr/src/main.rs:240:30
stack backtrace:
   0:        0x101786e95 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h66f38d4abb2e41c1
   1:        0x1017a94d0 - core::fmt::write::h4f487e714088986d
   2:        0x10178155b - std::io::Write::write_fmt::h7bd7b6fe8b47c5fb
   3:        0x10178919a - std::panicking::default_hook::{{closure}}::heee79636c241547c
   4:        0x101788ea5 - std::panicking::default_hook::hfcbd07059d15441e
   5:        0x101789867 - std::panicking::rust_panic_with_hook::h0c4b67125f55410a
   6:        0x1017af551 - std::panicking::begin_panic::h817647a7cd322460
   7:        0x100de69b0 - jormungandr::start_services::{{closure}}::{{closure}}::hbe6ccf2504f41799
   8:        0x100ea7e92 - std::panicking::try::do_call::h14fc7badb6d62f7a
   9:        0x10178d10f - __rust_maybe_catch_panic
  10:        0x100ee7472 - <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::h46dac3a96d1bb17b
  11:        0x100dc0cd2 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h25b5e4709dcfb12e
  12:        0x10105809b - futures::future::chain::Chain<A,B,C>::poll::h22b10e87d8543eeb
  13:        0x101767c4d - futures::task_impl::std::set::hf6a81d7ad603e678
  14:        0x1017677e6 - std::panicking::try::do_call::hcd8daf8285f047e0
  15:        0x10178d10f - __rust_maybe_catch_panic
  16:        0x10176724c - tokio_threadpool::task::Task::run::h760436a59674e20c
  17:        0x101761fe2 - tokio_threadpool::worker::Worker::run_task::ha7990cca7b384af0
  18:        0x101761650 - tokio_threadpool::worker::Worker::run::hcce58b75f670a94e
  19:        0x10174515d - std::thread::local::LocalKey<T>::with::h10e97151fce0e682
  20:        0x101745423 - std::thread::local::LocalKey<T>::with::h8bd1893f4e1dcef8
  21:        0x1017452d5 - std::thread::local::LocalKey<T>::with::h25cef123f17cae5c
  22:        0x101746f21 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h936dd1a535065305
  23:        0x101764cdb - std::thread::local::LocalKey<T>::with::h4ea373a2c47f8794
  24:        0x10176478b - std::thread::local::LocalKey<T>::with::h144e317d6ab1920c
  25:        0x10175df60 - std::sys_common::backtrace::__rust_begin_short_backtrace::h75b0980a2f3dd595
  26:        0x101767750 - std::panicking::try::do_call::h2b96ac45e1874e98
  27:        0x10178d10f - __rust_maybe_catch_panic
  28:        0x10175f8b7 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he746ca0ef6339ffd
  29:        0x10177a85e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd1afe4d791e3679f
  30:        0x10178c62e - std::sys::unix::thread::Thread::new::thread_start::h785fcf8d81bd0f52
  31:     0x7fff6b26cd36 - _pthread_start
Nov 23 09:30:22.282 CRIT Task panicked, task: network
Nov 23 09:30:22.282 INFO Shutting down node
Nov 23 09:30:23.714 WARN Shutting down service client-query (up since 38m 12s 959ms 337us 80ns): receiving on a closed channel, task: client-query

**Comment by mzabaluev** [comment]
Possible duplicate of #967.
#1178 fixes one possible cause of unbounded RAM usage.
