### ISSUE TITLE
thread 'block3' panicked at 'invalid key' v0.8.0

### ISSUE THREAD

**Issue by bobdobs** [input-output-hk/jormungandr#1350]
Version: jormungandr 0.8.0 (HEAD-7868354, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

Stack backtrace: 
```
stack backtrace:
   0:     0x55593e15e67c - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55593e15e67c - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55593e15e67c - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55593e15e67c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55593dae47ac - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55593e15de96 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55593e15db10 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55593e15db10 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55593e15db10 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55593e15d25f - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55593e15d25f - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55593dfde6a4 - std::panicking::begin_panic::he11d6503ce9e2932
  12:     0x55593dba91ec - tokio_timer::delay_queue::DelayQueue<T>::remove::hf70d8a4e0481f702
  13:     0x55593e047c24 - jormungandr::blockchain::candidate::CandidateForestThickets::remove_root::h0ef473e78ff693a0
  14:     0x55593dc6e8fd - <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll::h04e22abc9a2524c1
  15:     0x55593d947b19 - futures::future::chain::Chain<A,B,C>::poll::hc86b191761b62ba6
  16:     0x55593d97600d - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::hf8396ca6d95f35be
  17:     0x55593e1aff1e - futures::task_impl::std::set::h1bd778fe2d164d41
  18:     0x55593e1abf1c - tokio_threadpool::worker::Worker::run_task::h1508e513e3a67a63
  19:     0x55593e1ab406 - tokio_threadpool::worker::Worker::run::h0448d4fb460195e5
  20:     0x55593e18d00c - tokio_reactor::with_default::h71ab6fd20a390252
  21:     0x55593e18fee5 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h3d24c038b3dabae8
  22:     0x55593e1a83db - std::sys_common::backtrace::__rust_begin_short_backtrace::h8ad8da81466cd9cf
  23:     0x55593e1a9938 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb9854ca961872107
  24:     0x55593e16b28f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h483711add4ba2330
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  25:     0x55593e16cb3c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7605b45eb29ed0be
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  26:     0x55593e16cb3c - std::sys_common::thread::start_thread::h557b0c2dc4449562
                               at src/libstd/sys_common/thread.rs:13
  27:     0x55593e16cb3c - std::sys::unix::thread::Thread::new::thread_start::h7c2a7f9b68fe4bba
                               at src/libstd/sys/unix/thread.rs:79
  28:     0x7f63027b66ba - start_thread
  29:     0x7f63022d441d - clone
  30:                0x0 - <unknown>
```

**Comment by mzabaluev** [comment]
Should be fixed by #1346.

**Comment by stanfieldr** [comment]
I don't think this is fixed. I was monitoring my pool because it keeps forking and came across this issue. I was monitoring my node 1 second before I was supposed to be slot leader and 1 second after I should have completed the block using

```
#!/bin/bash
 
LAST_HASH=$(jcli rest v0 node stats get -h http://localhost:8300/api | grep lastBlockHash | awk '{print $2}')
LAST_TIME=$(jcli rest v0 node stats get -h http://localhost:8300/api | grep lastBlockTime | awk '{print $2}')
IOHK_LAST_HASH=$(curl -s 'https://explorer.incentivized-testnet.iohkdev.io/explorer/graphql' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H "Referer: https://shelleyexplorer.cardano.org/en/block/$LAST_HASH/" -H 'Content-Type: application/json' -H 'Origin: https://shelleyexplorer.cardano.org' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'TE: Trailers' --data "{\"query\":\"\n    query {\n      block (id: \\\"$LAST_HASH\\\") {\n        id\n      }\n    }\n  \"}" | grep "\"block\":{\"id\":\"$LAST_HASH\"")
 
echo "Checking hash $LAST_HASH"
echo "Last block time $LAST_TIME"
 
if [ -z "$IOHK_LAST_HASH" ]; then
        echo "Hash does not exists"
else
        echo "Hash exists"
fi
```

1 second before the schedule, it output hash exists. But then 1 second after it said it did not. I then went to a terminal screen running the jormungandr command and found this error there:

thread 'block1' panicked at 'invalid key', /cargo/registry/src/github.com-1ecc6299db9ec823/slab-0.4.2/src/lib.rs:789:18

Unfortunately I was not have RUST_BACKTRACE set.

**Comment by stanfieldr** [comment]
RUST_BACKTRACE
```
thread 'block0' panicked at 'invalid key', /cargo/registry/src/github.com-1ecc6299db9ec823/slab-0.4.2/src/lib.rs:789:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::begin_panic
  12: tokio_timer::delay_queue::DelayQueue<T>::remove
  13: jormungandr::blockchain::candidate::CandidateForestThickets::remove_root
  14: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll
  15: futures::future::chain::Chain<A,B,C>::poll
  16: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  17: futures::task_impl::std::set
  18: tokio_threadpool::worker::Worker::run_task
  19: tokio_threadpool::worker::Worker::run
  20: tokio_reactor::with_default
  21: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
A service has terminated with an error
```

**Comment by stanfieldr** [comment]
I see next release, fingers crossed

**Comment by rinor** [comment]
@bobdobs I think this was fixed. Check https://github.com/input-output-hk/jormungandr/issues/1381. If that is the case, can we close this issue please. Thank you.

**Comment by rinor** [comment]
Closing this once since v0.8.5 does not have this bug. This was an issue up to v0.8.2
