### ISSUE TITLE
Panic: transaction not found for utxo input

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/jormungandr#1382]
**Describe the bug**

```
Starting jormungandr 0.8.3 (, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
Node started without path to the stored secret keys (not a stake pool or a BFT leader)
storing blockchain in '"/var/lib/jormungandr/blocks.sqlite"'
connecting to bootstrap peer <IP1>:3000
initial bootstrap failed
connecting to bootstrap peer <IP2>:3000
initial bootstrap failed
thread 'main' panicked at 'transaction not found for utxo input', src/libcore/option.rs:1166:5
stack backtrace:
   0:     0x55e861a17d9b - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
   1:     0x55e861a17a76 - std::panicking::default_hook::h95a8f00337383d83
   2:     0x55e861a1850d - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
   3:     0x55e861a18092 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
   4:     0x55e861a17f76 - rust_begin_unwind
   5:     0x55e861a355dd - core::panicking::panic_fmt::h7e9f94035af782b3
   6:     0x55e861a35647 - core::option::expect_failed::h292a6217b603c24f
   7:     0x55e86109330a - <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next::h29e75c05d94502a2
   8:     0x55e8610a67f1 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h6f0dfc7efebf69ed
   9:     0x55e86119a1e9 - jormungandr::explorer::indexing::ExplorerTransaction::from::hdf92bf39f76da6a3
  10:     0x55e8614cea59 - <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::FromIterator<(K, V)>>::from_iter::h3148a910b5fb84e7
  11:     0x55e861199084 - jormungandr::explorer::indexing::ExplorerBlock::resolve_from::hb69f39dded433b2d
  12:     0x55e861335d7b - futures::future::chain::Chain<A,B,C>::poll::hf93acc7066651bbb
  13:     0x55e8613179e3 - futures::future::chain::Chain<A,B,C>::poll::hb99c30dd2ebda30d
  14:     0x55e861324d43 - futures::future::chain::Chain<A,B,C>::poll::hda102bdcdc41f067
  15:     0x55e861328d81 - futures::future::chain::Chain<A,B,C>::poll::hdd6d73a68ef2e797
  16:     0x55e8610466f7 - <futures::stream::fold::Fold<S,F,Fut,T> as futures::future::Future>::poll::h0fdde01463575fea
  17:     0x55e8612b948a - futures::future::chain::Chain<A,B,C>::poll::h31e76a8ed451c401
  18:     0x55e861033ad4 - futures::task_impl::std::set::hc1059c96b3f04ab8
  19:     0x55e8614dcb91 - std::thread::local::LocalKey<T>::with::h7d50d9a5f4d4661f
  20:     0x55e861544786 - futures::future::Future::wait::h1379ef649f605967
  21:     0x55e86115061b - jormungandr::explorer::ExplorerDB::bootstrap::h00e2c05b568a1d9a
  22:     0x55e861453d93 - jormungandr::main::hf8cc12a04d3c6bc9
  23:     0x55e861405263 - std::rt::lang_start::{{closure}}::h5d566cfea12f93ba
  24:     0x55e861a17f13 - std::panicking::try::do_call::h9440ccd4dc467eaa
  25:     0x55e861a1ccca - __rust_maybe_catch_panic
  26:     0x55e861a18add - std::rt::lang_start_internal::hea1b49a567afe309
  27:     0x55e861459bd2 - main
  28:     0x7f8840bc3b8e - __libc_start_main
  29:     0x55e860fec94a - _start
  30:                0x0 - <unknown>
jormungandr.service: Main process exited, code=exited, status=101/n/a
jormungandr.service: Failed with result 'exit-code'.
jormungandr.service: Consumed 19.275s CPU time, received 53.9M IP traffic, sent 602.1K IP traffic.
```

**Mandatory Information**
# jcli --full-version
jcli 0.8.3 (, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**Comment by NicolasDP** [comment]
@johnalotoski do you see this all the time when you boot your node? or only in some cases?

**Comment by rcmorano** [comment]
@NicolasDP it won't boot after that error happened once, got to remove the storage and sync from a different trusted peer

**Comment by rinor** [comment]
@NicolasDP is it possible this was side effect/caused by https://github.com/input-output-hk/jormungandr/issues/1326 (or similar) in cases of nodes with explorer enabled :see_no_evil:

**Comment by rinor** [comment]
Explorer node build from latest master https://github.com/input-output-hk/jormungandr/commit/bed450fd8ef92d204f03d235f7d02f31f669de82
yet to catch a panic in `main`, but caught panics in `explorer` thread.
```
thread 'explorer1' panicked at 'transaction not found for utxo input', src/libcore/option.rs:1190:5
stack backtrace:
thread 'explorer0' panicked at 'transaction not found for utxo input', src/libcore/option.rs:1190:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
   0:     0x55a306f1c744 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55a306f1c744 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55a306f1c744 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55a306f1c744 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55a306f4048c - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55a306f16c97 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55a306f1ec95 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55a306f1ec95 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55a306f1ec95 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55a306f1e986 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55a306f1f395 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55a306f1ef32 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x55a306f1ee26 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x55a306f3bffa - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x55a306f3c067 - core::option::expect_failed::h616db3795314a1d2
                               at src/libcore/option.rs:1190
  15:     0x55a3058dcaba - core::option::Option<T>::expect::h55454915b98b470f
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/option.rs:345
  16:     0x55a3054d7541 - jormungandr::explorer::indexing::ExplorerTransaction::from::{{closure}}::hca0958a2ff73da16
                               at jormungandr/src/explorer/indexing.rs:328
  17:     0x55a3054d0de2 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::hf0adb951fcb6cc1c
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ops/function.rs:265
  18:     0x55a305ae5a8c - core::iter::traits::iterator::Iterator::find_map::check::{{closure}}::h39d21f1a5fd785c2
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/traits/iterator.rs:2008
  19:     0x55a305adea81 - core::iter::traits::iterator::Iterator::try_for_each::call::{{closure}}::h5913fc96e48544d6
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/traits/iterator.rs:1733
  20:     0x55a305102443 - core::iter::traits::iterator::Iterator::try_fold::hb464d0681d01b1eb
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/traits/iterator.rs:1694
  21:     0x55a305100379 - core::iter::traits::iterator::Iterator::try_for_each::hbb33fb3895de6a5b
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/traits/iterator.rs:1736
  22:     0x55a30510069e - core::iter::traits::iterator::Iterator::find_map::h369493bedc6b51cb
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/traits/iterator.rs:2014
  23:     0x55a305b51f1a - <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next::h84ec807b2a69eaec
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/adapters/mod.rs:966
  24:     0x55a305236ff6 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::ha31f29dae64c9c3b
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/vec.rs:1923
  25:     0x55a30524c65d - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::hc23bee95af0b1b4c
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/vec.rs:1836
  26:     0x55a305b58c5d - core::iter::traits::iterator::Iterator::collect::hef4a35e979ad1eea
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/traits/iterator.rs:1478
  27:     0x55a3054d4198 - jormungandr::explorer::indexing::ExplorerTransaction::from::h2dccf48423431835
                               at jormungandr/src/explorer/indexing.rs:301
  28:     0x55a3054d3407 - jormungandr::explorer::indexing::ExplorerBlock::resolve_from::{{closure}}::h7c23c154b650d845
                               at jormungandr/src/explorer/indexing.rs:153
  29:     0x55a305b5ded7 - core::iter::adapters::filter_map_fold::{{closure}}::h28fefdbb93c94d1a
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/adapters/mod.rs:942
  30:     0x55a305b790d1 - <core::iter::adapters::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}::h44090efed836a53d
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/adapters/mod.rs:1119
  31:     0x55a304f011d7 - <core::slice::Iter<T> as core::iter::traits::iterator::Iterator>::fold::hd262c7d162727dcf
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:3213
  32:     0x55a305b78ffd - <core::iter::adapters::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::h6a97b677711cd81f
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/adapters/mod.rs:1126
  33:     0x55a305b51ad2 - <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::fold::h886894fed5e84212
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/adapters/mod.rs:986
  34:     0x55a305b59c40 - core::iter::traits::iterator::Iterator::for_each::h41bf8c22d7c91a06
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/traits/iterator.rs:616
  35:     0x55a3059c9e93 - <hashbrown::map::HashMap<K,V,S> as core::iter::traits::collect::Extend<(K, V)>>::extend::h4635ef28dd9ab211
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.5.0/src/map.rs:2466
  36:     0x55a305aceb8a - <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::Extend<(K, V)>>::extend::h50264141af1a7f6e
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/collections/hash/map.rs:2379
  37:     0x55a305aced36 - <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::FromIterator<(K, V)>>::from_iter::h676a2ad644e858e9
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/collections/hash/map.rs:2366
  38:     0x55a305b570d8 - core::iter::traits::iterator::Iterator::collect::h28c426b06e3667d5
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/iter/traits/iterator.rs:1478
  39:     0x55a30539bb4a - jormungandr::explorer::indexing::ExplorerBlock::resolve_from::hf432d07cba681b78
                               at jormungandr/src/explorer/indexing.rs:120
  40:     0x55a305aebac5 - jormungandr::explorer::ExplorerDB::apply_block::{{closure}}::h5bb842b91b630905
                               at jormungandr/src/explorer/mod.rs:252
  41:     0x55a305735664 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::{{closure}}::{{closure}}::h3fb55a67c49c0060
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/and_then.rs:34
  42:     0x55a305c001d4 - core::result::Result<T,E>::map::h4ba145a06f37bfad
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:512
  43:     0x55a30572f990 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::{{closure}}::h484f909829b67e84
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/and_then.rs:33
  44:     0x55a305149223 - futures::future::chain::Chain<A,B,C>::poll::h31432c744a8faa66
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:39
  45:     0x55a30572ce7d - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h5c3937c3bc4d2d00
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/and_then.rs:32
  46:     0x55a3051964cb - futures::future::chain::Chain<A,B,C>::poll::hc18be4a081dd7b40
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:26
  47:     0x55a30572c27d - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h01f0752922cb3dd4
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/and_then.rs:32
  48:     0x55a305166c96 - futures::future::chain::Chain<A,B,C>::poll::h5c6981ad1dd01f1a
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:26
  49:     0x55a30572d41d - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h8b55a6aa01aa6495
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/and_then.rs:32
  50:     0x55a30517d705 - futures::future::chain::Chain<A,B,C>::poll::h8f0fac3176029de3
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:26
  51:     0x55a305a45a86 - <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::h9baf9e0065cd48e5
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/then.rs:32
  52:     0x55a306ef6108 - <alloc::boxed::Box<F> as futures::future::Future>::poll::h9a2dafa0406a21ca
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
  53:     0x55a306e4cd34 - futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::h66b2361b3f08f928
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  54:     0x55a306e4cfe4 - futures::task_impl::Spawn<T>::enter::{{closure}}::h40eb32079fbfc0b5
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  55:     0x55a306e4d2d4 - futures::task_impl::std::set::hb41125b58e9af010
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83
  56:     0x55a306e4cf7f - futures::task_impl::Spawn<T>::enter::hd5c2809b69b8a9d5
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  57:     0x55a306e4cbd5 - futures::task_impl::Spawn<T>::poll_fn_notify::he5b36de1c8dca92b
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291
  58:     0x55a306e4cd08 - futures::task_impl::Spawn<T>::poll_future_notify::hcd64ced47b0b6e87
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  59:     0x55a306e37912 - tokio_threadpool::task::Task::run::{{closure}}::hbb8313cd0c806579
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/task/mod.rs:145
  60:     0x55a306e67199 - core::ops::function::FnOnce::call_once::h198b3cbedf48e4dd
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ops/function.rs:227
  61:     0x55a306e49369 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc3bd0173501609d3
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:315
  62:     0x55a306e73a79 - std::panicking::try::do_call::h1086c9b800841e32
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:292
  63:     0x55a306f2387a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  64:     0x55a306e738e0 - std::panicking::try::hdd9fdac19e51ec5e
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:271
  65:     0x55a306e499a1 - std::panic::catch_unwind::h079cc8026634b159
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:394
  66:     0x55a306e371ae - tokio_threadpool::task::Task::run::h6831b0793e4b7fd5
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/task/mod.rs:130
  67:     0x55a306e64b41 - tokio_threadpool::worker::Worker::run_task2::h7034b2b3e952b87e
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/worker/mod.rs:567
  68:     0x55a306e643b4 - tokio_threadpool::worker::Worker::run_task::hbe62cd2a5b54aa02
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/worker/mod.rs:459
  69:     0x55a306e63a27 - tokio_threadpool::worker::Worker::try_run_owned_task::hf8c0c89c027f9808
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/worker/mod.rs:390
  70:     0x55a306e6346d - tokio_threadpool::worker::Worker::try_run_task::hf2eb66ed39db5bc4
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/worker/mod.rs:297
  71:     0x55a306e632c6 - tokio_threadpool::worker::Worker::run::h7077827df884c91d
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/worker/mod.rs:241
  72:     0x55a306db9d9c - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hf721c4a853808f85
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:390
  73:     0x55a306dbd887 - tokio_timer::timer::handle::with_default::hfbc83167fa17d256
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.12/src/timer/handle.rs:74
  74:     0x55a306db9df9 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::h3ea195fad1db2363
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:382
  75:     0x55a306db05eb - tokio_timer::clock::clock::with_default::hdfe31d48e49674e3
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.12/src/clock/clock.rs:125
  76:     0x55a306db9e3a - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::h30071b9e43092ded
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:381
  77:     0x55a306db3e1b - tokio_reactor::with_default::hc7f9a3528f5af219
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.11/src/lib.rs:210
  78:     0x55a306db9ed5 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h1a82250f31b96fbb
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:380
  79:     0x55a306e57d63 - tokio_threadpool::callback::Callback::call::hf3fd3aca8d05c233
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/callback.rs:22
  80:     0x55a306e62f61 - tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::had071ff60d24c9c7
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/worker/mod.rs:127
  81:     0x55a306e4367b - tokio_executor::global::with_default::{{closure}}::h609d715f476946a3
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.9/src/global.rs:221
  82:     0x55a306e5f104 - std::thread::local::LocalKey<T>::try_with::h7d8b655ab2fecfe6
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:262
  83:     0x55a306e5ec53 - std::thread::local::LocalKey<T>::with::h6b5840c06899ac7e
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:239
  84:     0x55a306e43563 - tokio_executor::global::with_default::h96f81e64e05344ca
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.9/src/global.rs:190
  85:     0x55a306e6300d - tokio_threadpool::worker::Worker::do_run::{{closure}}::h5481440a9cb470e8
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/worker/mod.rs:125
  86:     0x55a306e5efb2 - std::thread::local::LocalKey<T>::try_with::h74f71eac8f63a42a
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:262
  87:     0x55a306e5ecbe - std::thread::local::LocalKey<T>::with::h943345803b1377a7
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:239
  88:     0x55a306e62e25 - tokio_threadpool::worker::Worker::do_run::h9d6ae295c2f6ce24
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/worker/mod.rs:116
  89:     0x55a306e708f0 - tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::hfdbb294a84f291a1
                               at /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.17/src/pool/mod.rs:345
  90:     0x55a306e7211e - std::sys_common::backtrace::__rust_begin_short_backtrace::hcf42fe591cee80bd
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/sys_common/backtrace.rs:126
  91:     0x55a306e55bb2 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hedb48e6bd8b94b74
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/mod.rs:470
  92:     0x55a306e49332 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h768772e213e542e4
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:315
  93:     0x55a306e73b03 - std::panicking::try::do_call::h1a7b8f30ec9ccd55
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:292
  94:     0x55a306f2387a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  95:     0x55a306e73716 - std::panicking::try::hbd411e273a35f4a8
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:271
  96:     0x55a306e499e2 - std::panic::catch_unwind::h4b7418d72ca983ca
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:394
  97:     0x55a306e55996 - std::thread::Builder::spawn_unchecked::{{closure}}::ha15b4ce39046557b
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/mod.rs:469
  98:     0x55a306e67094 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h5356c3708fbaa6e7
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ops/function.rs:227
  99:     0x55a306f0faef - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h483711add4ba2330
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
 100:     0x55a306f22be0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7605b45eb29ed0be
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
 101:     0x55a306f22be0 - std::sys_common::thread::start_thread::h557b0c2dc4449562
                               at src/libstd/sys_common/thread.rs:13
 102:     0x55a306f22be0 - std::sys::unix::thread::Thread::new::thread_start::h7c2a7f9b68fe4bba
                               at src/libstd/sys/unix/thread.rs:79
 103:     0x7f65456dcfa3 - start_thread
 104:     0x7f65455f14cf - clone
 105:                0x0 - <unknown>
thread 'explorer0' panicked at 'transaction not found for utxo input', src/libcore/option.rs:1190:5
thread 'explorer0' panicked at 'transaction not found for utxo input', src/libcore/option.rs:1190:5
```
Full log [itn_v1.transaction_not_found_for_utxo_input.log](https://github.com/input-output-hk/jormungandr/files/3974296/itn_v1.transaction_not_found_for_utxo_input.log)
