### ISSUE TITLE
thread 'block0' panicked /src/wheel/mod.rs:244:5

### ISSUE THREAD

**Issue by cardanoinvest** [input-output-hk/jormungandr#1473]
**Describe the bug**
thread 'block0' panicked at 'elapsed=6788032; when=6788032', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.12/src/wheel/mod.rs:244:5
stack backtrace:
   0:     0x55bd5d482b54 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55bd5d482b54 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55bd5d482b54 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55bd5d482b54 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55bd5d4a6b8c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x55bd5d47d317 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x55bd5d4850ce - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55bd5d4850ce - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55bd5d4850ce - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x55bd5d484dc1 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x55bd5d4857cb - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x55bd5d48536e - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x55bd5d4852af - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
  13:     0x55bd5d443b60 - tokio_timer::wheel::level_for::h371c25c0814fb006
  14:     0x55bd5cbc30d7 - tokio_timer::wheel::Wheel<T>::remove::hd31bc9d66d2b0810
  15:     0x55bd5ca99c8d - tokio_timer::delay_queue::DelayQueue<T>::remove::h8bc99500c836b47a
  16:     0x55bd5caf04c5 - alloc::vec::Vec<T>::retain::h8b7c7225448931ef
  17:     0x55bd5cc7710d - <jormungandr::utils::fire_forget_scheduler::FireForgetSchedulerFuture<TID,WID,Data,Launcher> as futures::future::Future>::poll::h9550857804f55182
  18:     0x55bd5cde0332 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h0396a07a7ed4e99e
  19:     0x55bd5d4619c2 - futures::task_impl::std::set::h7c919cd004e9a886
  20:     0x55bd5d4616a2 - std::panicking::try::do_call::h6adfdd8329e42457
  21:     0x55bd5d489f9a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  22:     0x55bd5d45e689 - tokio_threadpool::task::Task::run::h910998a9042c4ac0
  23:     0x55bd5d45b89a - tokio_threadpool::worker::Worker::run_task::ha9c5642855884f92
  24:     0x55bd5d45ad20 - tokio_threadpool::worker::Worker::run::hce824d1fde1e89c8
  25:     0x55bd5d4375bc - tokio_reactor::with_default::hd7f385a1ff9fb8d6
  26:     0x55bd5d43b99f - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h9628c3bd722db038
  27:     0x55bd5d460efa - std::thread::local::LocalKey<T>::with::he948cbf53faee7ef
  28:     0x55bd5d460ce9 - std::thread::local::LocalKey<T>::with::ha8a13c4a637068de
  29:     0x55bd5d457fa8 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd5021da8505c07af
  30:     0x55bd5d4615fc - std::panicking::try::do_call::h01efb03db02007c9
  31:     0x55bd5d489f9a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  32:     0x55bd5d458af0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h076d991dcbbfee46
  33:     0x55bd5d475c7f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h3534c64212330b0c
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
  34:     0x55bd5d489080 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h338c10574a337ece
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
  35:     0x55bd5d489080 - std::sys_common::thread::start_thread::h761ac6d57710d65d
                               at src/libstd/sys_common/thread.rs:13
  36:     0x55bd5d489080 - std::sys::unix::thread::Thread::new::thread_start::h61c012ef60f933c0
                               at src/libstd/sys/unix/thread.rs:79
  37:     0x7f7727ebfe65 - start_thread
  38:     0x7f77279d288d - clone
  39:                0x0 - <unknown>
Dec 30 23:34:29.427 CRIT Task panicked, task: block

**Mandatory Information**
1. jcli 0.8.5 (HEAD-3db0680+, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.5 (HEAD-3db0680+, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
Running a stake pool, for few hours, happens every few hours.

**Comment by kakerley** [comment]
I have been having similar issues. Running Ubuntu Bionic and jormungandr 0.8.5. This happens several times a day.

Dec 31 05:01:40.705 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Dec 31 05:03:10.342 WARN request timed out or failed unexpectedly, error: Error(Elapsed), request: GetHeadersRange, task: client-query
thread 'block1' panicked at 'referential integrity failure in CandidateForest', src/libcore/option.rs:1185:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::option::expect_failed
             at src/libcore/option.rs:1185
  15: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll
  16: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  17: futures::task_impl::std::set
  18: tokio_threadpool::worker::Worker::run_task
  19: tokio_threadpool::worker::Worker::run
  20: tokio_reactor::with_default
  21: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Dec 31 05:04:02.590 CRIT Task panicked, task: block

**Comment by rcmorano** [comment]
I've also found one of my nodes stuck after hitting this. JFTR, I found API will return `Server Error: 500 Internal Server Error` after this crash.
