### ISSUE TITLE
tokio-runtime-worker-1' panicked at 'assertion failed: self.slab.is_empty()' causes thread 'main' panicked at 'internal error: entered unreachable code'

### ISSUE THREAD

**Issue by rinor** [input-output-hk/jormungandr#1510]
**Describe the bug**
Sometime during bootstrap the node panics and shuts down.
```
thread 'tokio-runtime-worker-1' panicked at 'assertion failed: self.slab.is_empty()', /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.1.26/src/proto/streams/store.rs:218:13
...
thread 'main' panicked at 'internal error: entered unreachable code', /home/rinor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/mod.rs:296:26
```
It may be related to the same causing https://github.com/input-output-hk/jormungandr/issues/881 and alike.

**Mandatory Information**
https://github.com/input-output-hk/jormungandr/commit/7f07ecabca0299149631f710924b30baf2a8b033

Debug log: [itn_v1_tokio_h2_slab_empty.log](https://github.com/input-output-hk/jormungandr/files/4027972/itn_v1_tokio_h2_slab_empty.log)

**Comment by Linicks** [comment]
I also experienced a similar issue while testing the recent master branch. 

**Mandatory Information:**
jormungandr 0.8.5 (master-7f07ecab, debug, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]


```
Jan 06 22:58:08.434 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Jan 06 22:58:11.034 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
Jan 06 22:58:41.293 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
thread 'network2' panicked at 'assertion failed: self.slab.is_empty()', /home/cardano/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.1.26/src/proto/streams/store.rs:218:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by rinor** [comment]
@Linicks while the cause is the same, your issue is a bit different, since depending when it happens may or may not cause severe issues. Thank you for reporting it.

**Comment by johnalotoski** [comment]
Here is another backtrace from v0.8.5 affecting the `networkX` thread: `jormungandr 0.8.5 (nix-build-3db0680, debug, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]`

```
move node to quarantine
failed to connect to peer
move node to quarantine
failed to connect to peer
move node to quarantine
failed to connect to peer
move node to quarantine
failed to connect to peer
move node to quarantine
incoming connection closed
thread 'network1' panicked at 'assertion failed: self.slab.is_empty()', /build/jormungandr-0.8.5-vendor/h2/src/proto/streams/store.rs:218:13
stack backtrace:
incoming connection on <IP>:3000
incoming connection closed
incoming connection on <IP>:3000
   0:     0x560260a1a7fb - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
   1:     0x560260a1a4d6 - std::panicking::default_hook::h95a8f00337383d83
   2:     0x560260a1af6d - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
   3:     0x560260875e15 - std::panicking::begin_panic::h71a1cedb55dd2b50
   4:     0x56026087377f - <h2::proto::streams::store::Store as core::ops::drop::Drop>::drop::h9662f095df2770ba
   5:     0x5602600595f1 - core::ptr::real_drop_in_place::hb03fa75afb774a3c
   6:     0x56026006402a - alloc::sync::Arc<T>::drop_slow::hb18738c1ffd432c8
   7:     0x56026014c96f - core::ptr::real_drop_in_place::hd99f2bf416ca816b
   8:     0x5602609f1df9 - core::ptr::real_drop_in_place::he3f7d0a29568ec09
   9:     0x5602609f2649 - tokio_threadpool::task::Task::run::h4db223cc4c4045b4
  10:     0x5602609ee0c1 - tokio_threadpool::worker::Worker::run_task::h2aa728a784a14290
  11:     0x5602609ed31e - tokio_threadpool::worker::Worker::run::h49145e0675d139a2
  12:     0x5602609c677e - tokio_timer::clock::clock::with_default::ha1f7719f998556e5
  13:     0x5602609cb233 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h3718af1987bc3877
  14:     0x5602609f455a - std::thread::local::LocalKey<T>::with::hc9597a85355907df
  15:     0x5602609f4349 - std::thread::local::LocalKey<T>::with::ha924dccce33d79cf
  16:     0x5602609ea479 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5f805ddce9866303
  17:     0x5602609f484c - std::panicking::try::do_call::hba27fc7a51dbc20a
  18:     0x560260a1f72a - __rust_maybe_catch_panic
  19:     0x5602609eb8b0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4fc133f0bd43ae4a
  20:     0x560260a0b28f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2877b2aefb0fd627
  21:     0x560260a1ea70 - std::sys::unix::thread::Thread::new::thread_start::h382c6ae14181d163
  22:     0x7f696f8e1ef7 - start_thread
  23:     0x7f696f5ff22f - __GI___clone
  24:                0x0 - <unknown>
received block announcement
received block announcement from network
block is already present
lifting quarantine
```

**Comment by mzabaluev** [comment]
These should not bother us since `h2` has been updated to 0.2.5 (https://github.com/hyperium/h2/issues/417).
