### ISSUE TITLE
v0.8.10 - thread 'thread '<unnamed>' panicked at 'failed to allocate an alternative stack

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/jormungandr#1792]
**Describe the bug**
Running v0.8.10 version of node on Centos (not stakepool); runs successfully for approximately 25 mintues and then fails with error:

`Feb 14 17:00:06.682 DEBG sending gossip to 43 peers, sub_task: send_gossip, task: network
thread 'thread '<unnamed>' panicked at 'failed to allocate an alternative stack', src/libstd/sys/unix/stack_overflow.rs:132:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
<unnamed>' panicked at 'failed to allocate an alternative stack', src/libstd/sys/unix/stack_overflow.rs:132:13
fatal runtime error: failed to initiate panic, error fatal runtime error: failed to initiate panic, error 5
`
(full log file attached)
[out_20_02_14_1602_01.log](https://github.com/input-output-hk/jormungandr/files/4206416/out_20_02_14_1602_01.log)

**Mandatory Information**
jcli 0.8.10 (HEAD-ed9f7550, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]
jormungandr 0.8.10 (HEAD-ed9f7550, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]

**To Reproduce**
1. Download and compile jormungandr
2. Run jormungandr with following command line options
` jormungandr --storage XXX --config "${HOME}/config/config.txt" --genesis-block-hash XXX`
(config file attached)
[config.txt](https://github.com/input-output-hk/jormungandr/files/4206412/config.txt)

3. Get error after 30 min execution approx

**Expected behavior**
No error

**Additional context**
Nope

**Comment by mzabaluev** [comment]
A possible way to troubleshoot this is to compile jormungandr with [abort on panic](https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/aborting-on-panic.html) and look at the thread stacks in the core dump.
