### ISSUE TITLE
Panic in logs during bootstrap with rest tls certificate 

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2130]
**Describe the bug**
When starting node with tls ceritifcate, there is panic in the logs:

```
thread 'tokio-runtime-worker' panicked at 'error binding to 127.0.0.1:9874: error creating server listener: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)', <::std::macros::panic macros>:5:6
stack backtrace:
   0:     0x7ff6bdf2a7b9 - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1:     0x7ff6bdf2a7b9 - std::sys_common::backtrace::_print_fmt
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:77
   2:     0x7ff6bdf2a7b9 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff6bdf42aeb - core::fmt::write
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\fmt\mod.rs:1052
   4:     0x7ff6bdf22524 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\io\mod.rs:1426
   5:     0x7ff6bdf2d43c - std::sys_common::backtrace::_print
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:62
   6:     0x7ff6bdf2d43c - std::sys_common::backtrace::print
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:49
   7:     0x7ff6bdf2d43c - std::panicking::default_hook::{{closure}}
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:204
   8:     0x7ff6bdf2d08c - std::panicking::default_hook
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:224
   9:     0x7ff6bdf2dc1f - std::panicking::rust_panic_with_hook
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:472
  10:     0x7ff6bdf2d7a5 - std::panicking::begin_panic_handler
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:380
  11:     0x7ff6bdf2d71c - std::panicking::begin_panic_fmt
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:334
  12:     0x7ff6bc5d6b0c - warp::server::{{impl}}::bind_with_graceful_shutdown::{{closure}}<warp::filter::boxed::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Eit
                               at <::std::macros::panic macros>:5
  13:     0x7ff6bc6c2a76 - core::result::Result<(std::net::addr::SocketAddr, hyper::server::Server<warp::tls::TlsAcceptor, hyper::service::make::MakeServiceFn<closure-0>, hyper::common::exec::Exec>), alloc::boxed::Box<Error>>::unwrap_or_else<(std::net::addr::SocketAddr, hyper::serv
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\result.rs:848
  14:     0x7ff6bc5d61db - warp::server::TlsServer<warp::filter::boxed::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\warp-0.2.2\src\server.rs:105
  15:     0x7ff6bc9568f3 - jormungandr::rest::run_server_with_app::{{closure}}<warp::filter::boxed::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::ge
                               at C:\Work\iohk\jormungandr\jormungandr\src\rest\mod.rs:79
  16:     0x7ff6bca6cc81 - std::future::{{impl}}::poll<generator-0>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\future.rs:43
  17:     0x7ff6bca4bb20 - std::future::poll_with_tls_context<std::future::GenFuture<generator-0>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\future.rs:98
  18:     0x7ff6bc954847 - jormungandr::rest::setup_cors::{{closure}}<warp::filter::boxed::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Ei
                               at C:\Work\iohk\jormungandr\jormungandr\src\rest\mod.rs:64
  19:     0x7ff6bca53a31 - std::future::{{impl}}::poll<generator-0>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\future.rs:43
  20:     0x7ff6bca4af40 - std::future::poll_with_tls_context<std::future::GenFuture<generator-0>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\future.rs:98
  21:     0x7ff6bc952d97 - jormungandr::rest::start_rest_server::{{closure}}
                               at C:\Work\iohk\jormungandr\jormungandr\src\rest\mod.rs:37
  22:     0x7ff6bca5cf71 - std::future::{{impl}}::poll<generator-0>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\future.rs:43
  23:     0x7ff6bca43120 - std::future::poll_with_tls_context<std::future::GenFuture<generator-0>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\future.rs:98
  24:     0x7ff6bcb36d1c - jormungandr::initialize_node::{{closure}}::{{closure}}
                               at C:\Work\iohk\jormungandr\jormungandr\src\main.rs:465
  25:     0x7ff6bca63681 - std::future::{{impl}}::poll<generator-0>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\future.rs:43
  26:     0x7ff6bca46510 - std::future::poll_with_tls_context<std::future::GenFuture<generator-0>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\future.rs:98
  27:     0x7ff6bc534299 - jormungandr::utils::task::{{impl}}::spawn_future_std::{{closure}}<closure-0,std::future::GenFuture<generator-0>>
                               at C:\Work\iohk\jormungandr\jormungandr\src\utils\task.rs:108
  28:     0x7ff6bca67e41 - std::future::{{impl}}::poll<generator-0>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\future.rs:43
  29:     0x7ff6bca44550 - std::future::poll_with_tls_context<std::future::GenFuture<generator-0>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\future.rs:98
  30:     0x7ff6bcb208c9 - tokio_compat::runtime::idle::{{impl}}::with::{{closure}}<(),std::future::GenFuture<generator-0>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-compat-0.1.5\src\runtime\idle.rs:65
  31:     0x7ff6bca5e221 - std::future::{{impl}}::poll<generator-0>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\future.rs:43
  32:     0x7ff6bc1beb67 - tokio::runtime::task::core::{{impl}}::poll::{{closure}}<std::future::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\core.rs:163
  33:     0x7ff6bc5fca55 - tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<std::future::GenFuture<generator-0>>>::with_mut<tokio::runtime::task::core::Stage<std::future::GenFuture<generator-0>>,core::task::poll::Poll<()>,closure-0>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\loom\std\unsafe_cell.rs:14
  34:     0x7ff6bc1bdcf6 - tokio::runtime::task::core::Core<std::future::GenFuture<generator-0>, alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::poll<std::future::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\core.rs:148
  35:     0x7ff6bbfd6869 - tokio::runtime::task::harness::{{impl}}::poll::{{closure}}<std::future::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\harness.rs:108
  36:     0x7ff6bccec84a - core::ops::function::FnOnce::call_once<closure-0,()>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\ops\function.rs:232
  37:     0x7ff6bc4b5505 - std::panic::{{impl}}::call_once<core::task::poll::Poll<core::result::Result<(), tokio::runtime::task::error::JoinError>>,closure-0>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panic.rs:318
  38:     0x7ff6bccc7ebb - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<(), tokio::runtime::task::error::JoinError>>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panicking.rs:305
  39:     0x7ff6bdf32ef2 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libpanic_unwind\lib.rs:86
  40:     0x7ff6bccc69b2 - std::panicking::try<core::task::poll::Poll<core::result::Result<(), tokio::runtime::task::error::JoinError>>,std::panic::AssertUnwindSafe<closure-0>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panicking.rs:281
  41:     0x7ff6bc4b7195 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<(), tokio::runtime::task::error::JoinError>>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panic.rs:394
  42:     0x7ff6bbfc2d85 - tokio::runtime::task::harness::Harness<std::future::GenFuture<generator-0>, alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::poll<std::future::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\harness.rs:84
  43:     0x7ff6bca24e42 - tokio::runtime::task::raw::poll<std::future::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\raw.rs:104
  44:     0x7ff6bdd16392 - tokio::runtime::task::raw::RawTask::poll
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\raw.rs:66
  45:     0x7ff6bdd501b7 - tokio::runtime::task::Notified<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::run<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\mod.rs:169
  46:     0x7ff6bdd260d9 - tokio::runtime::thread_pool::worker::{{impl}}::run_task::{{closure}}
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\thread_pool\worker.rs:308
  47:     0x7ff6bdd43333 - tokio::coop::budget::{{closure}}<closure-0,core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core>, ()>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\coop.rs:97
  48:     0x7ff6bdd6bb5d - std::thread::local::LocalKey<core::cell::Cell<usize>>::try_with<core::cell::Cell<usize>,closure-0,core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core>, ()>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\thread\local.rs:262
  49:     0x7ff6bdd6b197 - std::thread::local::LocalKey<core::cell::Cell<usize>>::with<core::cell::Cell<usize>,closure-0,core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core>, ()>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\thread\local.rs:239
  50:     0x7ff6bdd25f81 - tokio::coop::budget
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\coop.rs:79
  51:     0x7ff6bdd25f81 - tokio::runtime::thread_pool::worker::Context::run_task
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\thread_pool\worker.rs:307
  52:     0x7ff6bdd25992 - tokio::runtime::thread_pool::worker::Context::run
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\thread_pool\worker.rs:279
  53:     0x7ff6bdd25807 - tokio::runtime::thread_pool::worker::run::{{closure}}
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\thread_pool\worker.rs:264
  54:     0x7ff6bdd68baa - tokio::macros::scoped_tls::ScopedKey<tokio::runtime::thread_pool::worker::Context>::set<tokio::runtime::thread_pool::worker::Context,closure-0,()>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\macros\scoped_tls.rs:64
  55:     0x7ff6bdd25694 - tokio::runtime::thread_pool::worker::run
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\thread_pool\worker.rs:261
  56:     0x7ff6bdd25563 - tokio::runtime::thread_pool::worker::{{impl}}::launch::{{closure}}
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\thread_pool\worker.rs:240
  57:     0x7ff6bdd4ad1f - tokio::runtime::blocking::task::{{impl}}::poll<closure-0,()>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\blocking\task.rs:38
  58:     0x7ff6bdd4a577 - tokio::runtime::task::core::{{impl}}::poll::{{closure}}<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\core.rs:163
  59:     0x7ff6bdd3c705 - tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<closure-0>>>::with_mut<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<closure-0>>,core::task::poll::Po
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\loom\std\unsafe_cell.rs:14
  60:     0x7ff6bdd4a39f - tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<closure-0>, tokio::runtime::blocking::schedule::NoopSchedule>::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\core.rs:148
  61:     0x7ff6bdd90509 - tokio::runtime::task::harness::{{impl}}::poll::{{closure}}<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\harness.rs:108
  62:     0x7ff6bdd0d72a - core::ops::function::FnOnce::call_once<closure-0,()>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\ops\function.rs:232
  63:     0x7ff6bdd55085 - std::panic::{{impl}}::call_once<core::task::poll::Poll<core::result::Result<(), tokio::runtime::task::error::JoinError>>,closure-0>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panic.rs:318
  64:     0x7ff6bdd66a9b - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<(), tokio::runtime::task::error::JoinError>>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panicking.rs:305
  65:     0x7ff6bdf32ef2 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libpanic_unwind\lib.rs:86
  66:     0x7ff6bdd667b2 - std::panicking::try<core::task::poll::Poll<core::result::Result<(), tokio::runtime::task::error::JoinError>>,std::panic::AssertUnwindSafe<closure-0>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panicking.rs:281
  67:     0x7ff6bdd55b85 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<(), tokio::runtime::task::error::JoinError>>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panic.rs:394
  68:     0x7ff6bdd8fff5 - tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<closure-0>, tokio::runtime::blocking::schedule::NoopSchedule>::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedul
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\harness.rs:84
  69:     0x7ff6bdd16522 - tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\raw.rs:104
  70:     0x7ff6bdd16392 - tokio::runtime::task::raw::RawTask::poll
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\raw.rs:66
  71:     0x7ff6bdd50237 - tokio::runtime::task::Notified<tokio::runtime::blocking::schedule::NoopSchedule>::run<tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\task\mod.rs:169
  72:     0x7ff6bdd33fa1 - tokio::runtime::blocking::pool::Inner::run
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\blocking\pool.rs:230
  73:     0x7ff6bdd33d51 - tokio::runtime::blocking::pool::{{impl}}::spawn_thread::{{closure}}::{{closure}}
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\blocking\pool.rs:210
  74:     0x7ff6bdd42a26 - tokio::runtime::context::enter<closure-0,()>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\context.rs:72
  75:     0x7ff6bdd49b8a - tokio::runtime::handle::Handle::enter<closure-0,()>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\handle.rs:39
  76:     0x7ff6bdd33dea - tokio::runtime::blocking::pool::{{impl}}::spawn_thread::{{closure}}
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.18\src\runtime\blocking\pool.rs:209
  77:     0x7ff6bdd03453 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,()>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\sys_common\backtrace.rs:129
  78:     0x7ff6bdd573e3 - std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure-0,()>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\thread\mod.rs:475
  79:     0x7ff6bdd550c3 - std::panic::{{impl}}::call_once<(),closure-0>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panic.rs:318
  80:     0x7ff6bdd66ba9 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panicking.rs:305
  81:     0x7ff6bdf32ef2 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libpanic_unwind\lib.rs:86
  82:     0x7ff6bdd669aa - std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panicking.rs:281
  83:     0x7ff6bdd55b43 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\panic.rs:394
  84:     0x7ff6bdd5720b - std::thread::{{impl}}::spawn_unchecked::{{closure}}<closure-0,()>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\thread\mod.rs:474
  85:     0x7ff6bdd0d5f3 - core::ops::function::FnOnce::call_once<closure-0,()>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\ops\function.rs:232
  86:     0x7ff6bdf18567 - alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\liballoc\boxed.rs:1015
  87:     0x7ff6bdf30e57 - alloc::boxed::{{impl}}::call_once
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\liballoc\boxed.rs:1015
  88:     0x7ff6bdf30e57 - std::sys_common::thread::start_thread
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\thread.rs:13
  89:     0x7ff6bdf30e57 - std::sys::windows::thread::{{impl}}::new::thread_start
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys\windows\thread.rs:51
  90:     0x7ffac6357bd4 - BaseThreadInitThunk
  91:     0x7ffac822ce51 - RtlUserThreadStart
```

**Mandatory Information**
1.`jcli 0.8.19-nightly (tls-7f16d3dfe+, debug, windows [x86_64]) - [rustc 1.42.0 (b8cedc004 2020-03-09)]`
2. j`ormungandr 0.8.19-nightly (tls-7f16d3dfe+, debug, windows [x86_64]) - [rustc 1.42.0 (b8cedc004 2020-03-09)]`

**To Reproduce**
1. Perform steps from guide: https://input-output-hk.github.io/jormungandr/configuration/network.html?highlight=tls#configuring-tls
2. Start node as leader

**Expected behavior**
Node start succesfully

**Additional context**
see pr with #2112 automated test case : ` cargo test test_rest_tls_config -- --nocapture`
[node_config.txt](https://github.com/input-output-hk/jormungandr/files/4528180/node_config.txt)

**Comment by dkijania** [comment]
fixed by #2740
