### ISSUE TITLE
v0.9.0-rc2 - Explorer - thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: EntryExists', jormungandr/src/explorer/mod.rs:639:84

### ISSUE THREAD

**Issue by rinor** [input-output-hk/jormungandr#2426]
**Describe the bug**
Explorer panic. After that panic the logs are filled with errors like:

```
Jun 24 11:22:48.009 ERRO Explorer error: ancestor of block 'e763a0f5385d6c33c88bd46addc71ee46ed20a8162cfa5926d6b901696f9a6da' cannot be found in the explorer, task: explorer
Jun 24 11:22:48.009 ERRO apply block finished with error, error: (), task: explorer
```

**Mandatory Information**
1. `jcli 0.9.0-rc2.20200622 (master-75ce024, release, linux [x86_64]) - [rustc 1.44.1 (c7087fe00 2020-06-17)]`
2. `jormungandr 0.9.0-rc2.20200622 (master-75ce024, release, linux [x86_64]) - [rustc 1.44.1 (c7087fe00 2020-06-17)]`

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: EntryExists', jormungandr/src/explorer/mod.rs:639:84
stack backtrace:
   0:     0x564a257a0a7d - backtrace::backtrace::libunwind::trace::h812748238d609e46
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x564a257a0a7d - backtrace::backtrace::trace_unsynchronized::h7c97e818aebf09c8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x564a257a0a7d - std::sys_common::backtrace::_print_fmt::h60d914263b0ccd71
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x564a257a0a7d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf78227137afc7565
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x564a24f064ac - core::fmt::write::h543cdf60775f89bf
                               at src/libcore/fmt/mod.rs:1069
   5:     0x564a257a01c4 - std::io::Write::write_fmt::h0c7f3ce24c679426
                               at src/libstd/io/mod.rs:1504
   6:     0x564a2579f9b5 - std::sys_common::backtrace::_print::h80e55e24be231368
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x564a2579f9b5 - std::sys_common::backtrace::print::h3b197b9c1261c865
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x564a2579f9b5 - std::panicking::default_hook::{{closure}}::ha6c807149ce20f8f
                               at src/libstd/panicking.rs:198
   9:     0x564a2579ef41 - std::panicking::default_hook::he49a9c12e358cc45
                               at src/libstd/panicking.rs:218
  10:     0x564a2579ef41 - std::panicking::rust_panic_with_hook::h93f74f5ef2f71f31
                               at src/libstd/panicking.rs:511
  11:     0x564a2579ead8 - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x564a24f03cd0 - core::panicking::panic_fmt::h1ce7d3a6bb2a90c1
                               at src/libcore/panicking.rs:111
  13:     0x564a24f0a932 - core::option::expect_none_failed::hb01994a49b20448c
                               at src/libcore/option.rs:1268
  14:     0x564a252607c7 - jormungandr::explorer::apply_block_to_vote_plans::{{closure}}::h7dd36f54c734705a
  15:     0x564a2525fdaa - imhamt::node::reference::update_rec::h85640d36e588e839
  16:     0x564a25144f12 - jormungandr::explorer::apply_block_to_vote_plans::h670b4e4e51b0b27f
  17:     0x564a251bd3ec - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc5fec0ab1bbd4c02
  18:     0x564a250c146f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4f9e3d27dcf0c876
  19:     0x564a25484ac1 - tokio::runtime::task::raw::poll::h65a7373b9a675edb
  20:     0x564a257e2e6e - tokio::runtime::thread_pool::worker::Context::run_task::h7c0934738c3073bd
  21:     0x564a257d541e - tokio::runtime::task::raw::poll::hb9f5cd5f37bec190
  22:     0x564a257d1df6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h80a2728e2bb50bb4
  23:     0x564a257e0814 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hca90fd1648f6c5bd
  24:     0x564a257b662a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf207c3654ee300a0
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  25:     0x564a257b662a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h66e0c6190e34816b
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  26:     0x564a257b662a - std::sys::unix::thread::Thread::new::thread_start::h30687bc0b1c3cd55
                               at src/libstd/sys/unix/thread.rs:87
  27:     0x7ffa116da6db - start_thread
  28:     0x7ffa111eb88f - __clone
  29:                0x0 - <unknown>
```

**Comment by rinor** [comment]
Even if we try to restart the node with the explorer enabled, it panics and the node shuts down
```
Jun 25 13:59:42.699 INFO loading from storage, currently at af1c3224-00022ca5-6.12907 processing=132.959381ms (53.183µs per block) ..., task: bootstrap
Jun 25 13:59:42.733 INFO Loaded from storage tip is : 5d1f42f0-00022e3b-6.13313, task: bootstrap
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EntryExists', jormungandr/src/explorer/mod.rs:639:84
stack backtrace:
   0:     0x5566830a9a7d - backtrace::backtrace::libunwind::trace::h812748238d609e46
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5566830a9a7d - backtrace::backtrace::trace_unsynchronized::h7c97e818aebf09c8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5566830a9a7d - std::sys_common::backtrace::_print_fmt::h60d914263b0ccd71
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5566830a9a7d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf78227137afc7565
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55668280f4ac - core::fmt::write::h543cdf60775f89bf
                               at src/libcore/fmt/mod.rs:1069
   5:     0x5566830a91c4 - std::io::Write::write_fmt::h0c7f3ce24c679426
                               at src/libstd/io/mod.rs:1504
   6:     0x5566830a89b5 - std::sys_common::backtrace::_print::h80e55e24be231368
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5566830a89b5 - std::sys_common::backtrace::print::h3b197b9c1261c865
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5566830a89b5 - std::panicking::default_hook::{{closure}}::ha6c807149ce20f8f
                               at src/libstd/panicking.rs:198
   9:     0x5566830a7f41 - std::panicking::default_hook::he49a9c12e358cc45
                               at src/libstd/panicking.rs:218
  10:     0x5566830a7f41 - std::panicking::rust_panic_with_hook::h93f74f5ef2f71f31
                               at src/libstd/panicking.rs:511
  11:     0x5566830a7ad8 - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x55668280ccd0 - core::panicking::panic_fmt::h1ce7d3a6bb2a90c1
                               at src/libcore/panicking.rs:111
  13:     0x556682813932 - core::option::expect_none_failed::hb01994a49b20448c
                               at src/libcore/option.rs:1268
  14:     0x556682b697c7 - jormungandr::explorer::apply_block_to_vote_plans::{{closure}}::h7dd36f54c734705a
  15:     0x556682b68daa - imhamt::node::reference::update_rec::h85640d36e588e839
  16:     0x556682a4df12 - jormungandr::explorer::apply_block_to_vote_plans::h670b4e4e51b0b27f
  17:     0x556682ac63ec - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc5fec0ab1bbd4c02
  18:     0x556682dcca12 - <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll::h372453a6366f402f
  19:     0x5566828ff055 - jormungandr::bootstrap_internal::{{closure}}::{{closure}}::{{closure}}::h82ee58ad3fb61d45
  20:     0x556682aa9260 - jormungandr::bootstrap_internal::{{closure}}::hd78199c1e6c81b3e
  21:     0x556682bea1ac - std::thread::local::LocalKey<T>::with::h2fadb25ce44a4117
  22:     0x556682e59baf - tokio::runtime::enter::Enter::block_on::h3b3d0229dd69453a
  23:     0x556682c357c6 - tokio::runtime::thread_pool::ThreadPool::block_on::h7ae751bb61c267e2
  24:     0x5566826f2f1e - tokio::runtime::context::enter::he43858dd52bdc7be
  25:     0x556682b8ce26 - jormungandr::start::hc320dc5edaba84d2
  26:     0x556682b83ee5 - jormungandr::main::h93fc7998298277a5
  27:     0x5566830bdea3 - std::rt::lang_start_internal::{{closure}}::{{closure}}::h4ed4ab1fb893cc93
                               at src/libstd/rt.rs:52
  28:     0x5566830bdea3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1f01c818c00c4f70
                               at src/libstd/sys_common/backtrace.rs:130
  29:     0x5566830bd802 - std::rt::lang_start_internal::{{closure}}::h44dc84346eeba462
                               at src/libstd/rt.rs:52
  30:     0x5566830bd802 - std::panicking::try::do_call::h3559ee6be71549e2
                               at src/libstd/panicking.rs:331
  31:     0x5566830bd802 - std::panicking::try::h78f4c77016541848
                               at src/libstd/panicking.rs:274
  32:     0x5566830bd802 - std::panic::catch_unwind::hfe46f382761b3d41
                               at src/libstd/panic.rs:394
  33:     0x5566830bd802 - std::rt::lang_start_internal::he05790f0cb2000df
                               at src/libstd/rt.rs:51
  34:     0x556682b83ec4 - main
  35:     0x7f6674927b97 - __libc_start_main
  36:     0x5566826b03ea - _start
  37:                0x0 - <unknown>
```

**Comment by rinor** [comment]
fixed on https://github.com/input-output-hk/jormungandr/pull/2427
