### ISSUE TITLE
Explorer panic during e2e vote flow

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2553]
**Describe the bug**
An ugly panic is printed on console while running test `test_vote_flow_bft` from PR `https://github.com/input-output-hk/jormungandr/pull/2552`

**Mandatory Information**
1. `jcli --full-version` newest master;
2. `jormungandr --full-version` newest master;

**To Reproduce**
1. checkout #2552 
2.  `cargo test test_vote_flow_bft -- --nocapture`
3. See error:

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', jormungandr\src\explorer\mod.rs:682:50
stack backtrace:
   0:     0x7ff61d689f3e - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1:     0x7ff61d689f3e - std::sys_common::backtrace::_print_fmt
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\sys_common\backtrace.rs:78
   2:     0x7ff61d689f3e - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff61d6a324c - core::fmt::write
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libcore\fmt\mod.rs:1076
   4:     0x7ff61d681bc3 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\io\mod.rs:1537
   5:     0x7ff61d68d14b - std::sys_common::backtrace::_print
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\sys_common\backtrace.rs:62
   6:     0x7ff61d68d14b - std::sys_common::backtrace::print
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\sys_common\backtrace.rs:49
   7:     0x7ff61d68d14b - std::panicking::default_hook::{{closure}}
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\panicking.rs:198
   8:     0x7ff61d68cd98 - std::panicking::default_hook
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\panicking.rs:217
   9:     0x7ff61d68d91f - std::panicking::rust_panic_with_hook
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\panicking.rs:526
  10:     0x7ff61d68d49f - std::panicking::begin_panic_handler
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\panicking.rs:437
  11:     0x7ff61d6a0da0 - core::panicking::panic_fmt
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libcore\panicking.rs:85
  12:     0x7ff61d6a0cec - core::panicking::panic
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libcore\panicking.rs:50
  13:     0x7ff61b8c3161 - core::option::Option<chain_impl_mockchain::vote::tally::Tally>::unwrap<chain_impl_mockchain::vote::tally::Tally>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\macros\mod.rs:10
  14:     0x7ff61c0e6e92 - jormungandr::explorer::apply_block_to_vote_plans::{{closure}}::{{closure}}
                               at C:\Work\iohk\jormungandr\jormungandr\src\explorer\mod.rs:679
  15:     0x7ff61b6ee9ce - core::iter::adapters::map_fold::{{closure}}<tuple<usize, jormungandr::explorer::indexing::ExplorerVoteProposal>,jormungandr::explorer::indexing::ExplorerVoteProposal,tuple<>,closure-1,closure-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:833
  16:     0x7ff61b708b49 - core::iter::adapters::{{impl}}::fold::enumerate::{{closure}}<jormungandr::explorer::indexing::ExplorerVoteProposal,tuple<>,closure-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:1300
  17:     0x7ff61b71d6cd - core::iter::traits::iterator::Iterator::fold<alloc::vec::IntoIter<jormungandr::explorer::indexing::ExplorerVoteProposal>,tuple<>,closure-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\traits\iterator.rs:2022
  18:     0x7ff61b708869 - core::iter::adapters::{{impl}}::fold<alloc::vec::IntoIter<jormungandr::explorer::indexing::ExplorerVoteProposal>,tuple<>,closure-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:1307
  19:     0x7ff61b6fdf6d - core::iter::adapters::{{impl}}::fold<jormungandr::explorer::indexing::ExplorerVoteProposal,core::iter::adapters::Enumerate<alloc::vec::IntoIter<jormungandr::explorer::indexing::ExplorerVoteProposal>>,closure-1,tuple<>,closure-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:873
  20:     0x7ff61b6e06ee - core::iter::traits::iterator::Iterator::for_each<core::iter::adapters::Map<core::iter::adapters::Enumerate<alloc::vec::IntoIter<jormungandr::explorer::indexing::ExplorerVoteProposal>>, closure-1>,closure-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\traits\iterator.rs:658
  21:     0x7ff61b7571f3 - alloc::vec::{{impl}}::spec_extend<jormungandr::explorer::indexing::ExplorerVoteProposal,core::iter::adapters::Map<core::iter::adapters::Enumerate<alloc::vec::IntoIter<jormungandr::explorer::indexing::ExplorerVoteProposal>>, closure-1>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\liballoc\vec.rs:2140
  22:     0x7ff61b76a37a - alloc::vec::{{impl}}::from_iter<jormungandr::explorer::indexing::ExplorerVoteProposal,core::iter::adapters::Map<core::iter::adapters::Enumerate<alloc::vec::IntoIter<jormungandr::explorer::indexing::ExplorerVoteProposal>>, closure-1>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\liballoc\vec.rs:2120
  23:     0x7ff61b77a980 - alloc::vec::{{impl}}::from_iter<jormungandr::explorer::indexing::ExplorerVoteProposal,core::iter::adapters::Map<core::iter::adapters::Enumerate<alloc::vec::IntoIter<jormungandr::explorer::indexing::ExplorerVoteProposal>>, closure-1>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\liballoc\vec.rs:1995
  24:     0x7ff61b6d9d0e - core::iter::traits::iterator::Iterator::collect<core::iter::adapters::Map<core::iter::adapters::Enumerate<alloc::vec::IntoIter<jormungandr::explorer::indexing::ExplorerVoteProposal>>, closure-1>,alloc::vec::Vec<jormungandr::explorer::indexing::ExplorerVot
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\traits\iterator.rs:1671
  25:     0x7ff61c0e7199 - jormungandr::explorer::apply_block_to_vote_plans::{{closure}}
                               at C:\Work\iohk\jormungandr\jormungandr\src\explorer\mod.rs:671
  26:     0x7ff61be7308d - imhamt::node::reference::update_rec<chain_crypto::digest::DigestOf<chain_crypto::hash::Blake2b256, chain_impl_mockchain::certificate::vote_plan::VotePlan>,alloc::sync::Arc<jormungandr::explorer::indexing::ExplorerVotePlan>,closure-2,core::convert::Infalli
                               at C:\Work\iohk\jormungandr\chain-deps\imhamt\src\node\reference.rs:440
  27:     0x7ff61bb1075c - imhamt::hamt::Hamt<std::collections::hash::map::DefaultHasher, chain_crypto::digest::DigestOf<chain_crypto::hash::Blake2b256, chain_impl_mockchain::certificate::vote_plan::VotePlan>, alloc::sync::Arc<jormungandr::explorer::indexing::ExplorerVotePlan>>::up
                               at C:\Work\iohk\jormungandr\chain-deps\imhamt\src\hamt.rs:126
  28:     0x7ff61b9905b8 - jormungandr::explorer::apply_block_to_vote_plans
                               at C:\Work\iohk\jormungandr\jormungandr\src\explorer\mod.rs:658
  29:     0x7ff61c0dc702 - jormungandr::explorer::{{impl}}::apply_block::{{closure}}
                               at C:\Work\iohk\jormungandr\jormungandr\src\explorer\mod.rs:283
  30:     0x7ff61bae96c3 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:78
  31:     0x7ff61b9bd985 - futures_util::future::future::map::{{impl}}::poll<core::future::from_generator::GenFuture<generator-0>,closure-0,core::result::Result<tuple<>, tuple<>>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.5\src\future\future\map.rs:67
  32:     0x7ff61c583fec - futures_util::future::future::{{impl}}::poll<core::future::from_generator::GenFuture<generator-0>,closure-0>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.5\src\lib.rs:107
  33:     0x7ff61c0d7754 - jormungandr::explorer::{{impl}}::start::{{closure}}::{{closure}}::{{closure}}::{{closure}}
                               at C:\Work\iohk\jormungandr\jormungandr\src\explorer\mod.rs:122
  34:     0x7ff61bad7829 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:78
  35:     0x7ff61b9fb4fd - jormungandr::utils::task::{{impl}}::spawn_fallible::{{closure}}<core::future::from_generator::GenFuture<generator-0>,tuple<>>
                               at C:\Work\iohk\jormungandr\jormungandr\src\utils\task.rs:236
  36:     0x7ff61bae3ed9 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:78
  37:     0x7ff61c35944f - tokio::runtime::task::core::{{impl}}::poll::{{closure}}<core::future::from_generator::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:173
  38:     0x7ff61bb8f1fa - tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<core::future::from_generator::GenFuture<generator-0>>>::with_mut<tokio::runtime::task::core::Stage<core::future::from_generator::GenFuture<generator-0>>,core::task::poll::Poll<tup
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\loom\std\unsafe_cell.rs:14
  39:     0x7ff61c354e09 - tokio::runtime::task::core::Core<core::future::from_generator::GenFuture<generator-0>, alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::poll<core::future::from_generator::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:158
  40:     0x7ff61c4f10e1 - tokio::runtime::task::harness::{{impl}}::poll::{{closure}}<core::future::from_generator::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:107
  41:     0x7ff61bcf1dea - core::ops::function::FnOnce::call_once<closure-0,tuple<>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:233
  42:     0x7ff61b8dcecb - std::panic::{{impl}}::call_once<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,closure-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  43:     0x7ff61c407ec0 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:348
  44:     0x7ff61c417b87 - std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
  45:     0x7ff61c3ffb42 - std::panicking::try<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,std::panic::AssertUnwindSafe<closure-0>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:325
  46:     0x7ff61b8dedeb - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  47:     0x7ff61c4e0a2b - tokio::runtime::task::harness::Harness<core::future::from_generator::GenFuture<generator-0>, alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::poll<core::future::from_generator::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:89
  48:     0x7ff61c3c9102 - tokio::runtime::task::raw::poll<core::future::from_generator::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:104
  49:     0x7ff61d1b0d9d - tokio::runtime::task::raw::RawTask::poll
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:66
  50:     0x7ff61d17ec07 - tokio::runtime::task::Notified<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::run<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\mod.rs:169
  51:     0x7ff61d16e532 - tokio::runtime::thread_pool::worker::{{impl}}::run_task::{{closure}}
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:374
  52:     0x7ff61d17bdd6 - tokio::coop::with_budget::{{closure}}<core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core>, tuple<>>,closure-0>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\coop.rs:127
  53:     0x7ff61d16a5c4 - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core>, tuple<>>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:263
  54:     0x7ff61d167edd - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core>, tuple<>>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:239
  55:     0x7ff61d16e209 - tokio::coop::with_budget
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\coop.rs:120
  56:     0x7ff61d16e209 - tokio::coop::budget
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\coop.rs:96
  57:     0x7ff61d16e209 - tokio::runtime::thread_pool::worker::Context::run_task
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:352
  58:     0x7ff61d16dd93 - tokio::runtime::thread_pool::worker::Context::run
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:324
  59:     0x7ff61d16dc1f - tokio::runtime::thread_pool::worker::run::{{closure}}
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:309
  60:     0x7ff61d17b479 - tokio::macros::scoped_tls::ScopedKey<tokio::runtime::thread_pool::worker::Context>::set<tokio::runtime::thread_pool::worker::Context,closure-0,tuple<>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\macros\scoped_tls.rs:63
  61:     0x7ff61d16dae3 - tokio::runtime::thread_pool::worker::run
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:306
  62:     0x7ff61d16d9ce - tokio::runtime::thread_pool::worker::{{impl}}::launch::{{closure}}
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:285
  63:     0x7ff61d1b27eb - tokio::runtime::blocking::task::{{impl}}::poll<closure-0,tuple<>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\task.rs:41
  64:     0x7ff61d19102f - tokio::runtime::task::core::{{impl}}::poll::{{closure}}<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:173
  65:     0x7ff61d1bb3ca - tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<closure-0>>>::with_mut<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<closure-0>>,core::task::poll::Po
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\loom\std\unsafe_cell.rs:14
  66:     0x7ff61d190e6f - tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<closure-0>, tokio::runtime::blocking::schedule::NoopSchedule>::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:158
  67:     0x7ff61d1f7de1 - tokio::runtime::task::harness::{{impl}}::poll::{{closure}}<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:107
  68:     0x7ff61d1a726a - core::ops::function::FnOnce::call_once<closure-0,tuple<>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:233
  69:     0x7ff61d18032b - std::panic::{{impl}}::call_once<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,closure-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  70:     0x7ff61d171e10 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:348
  71:     0x7ff61d17a0e7 - tokio::time::instant::{{impl}}::gt
  72:     0x7ff61d171b32 - std::panicking::try<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,std::panic::AssertUnwindSafe<closure-0>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:325
  73:     0x7ff61d180c7b - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  74:     0x7ff61d1f79db - tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<closure-0>, tokio::runtime::blocking::schedule::NoopSchedule>::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedul
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:89
  75:     0x7ff61d1b0f32 - tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:104
  76:     0x7ff61d1b0d9d - tokio::runtime::task::raw::RawTask::poll
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:66
  77:     0x7ff61d17eb87 - tokio::runtime::task::Notified<tokio::runtime::blocking::schedule::NoopSchedule>::run<tokio::runtime::blocking::schedule::NoopSchedule>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\mod.rs:169
  78:     0x7ff61d1b2123 - tokio::runtime::blocking::pool::Inner::run
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\pool.rs:230
  79:     0x7ff61d1b1ec1 - tokio::runtime::blocking::pool::{{impl}}::spawn_thread::{{closure}}::{{closure}}
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\pool.rs:210
  80:     0x7ff61d198d16 - tokio::runtime::context::enter<closure-0,tuple<>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\context.rs:72
  81:     0x7ff61d199537 - tokio::runtime::handle::Handle::enter<closure-0,tuple<>>
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\handle.rs:76
  82:     0x7ff61d1b1f53 - tokio::runtime::blocking::pool::{{impl}}::spawn_thread::{{closure}}
                               at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\pool.rs:209
  83:     0x7ff61d1cd1f3 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,tuple<>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\sys_common\backtrace.rs:130
  84:     0x7ff61d1e78e3 - std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure-0,tuple<>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\mod.rs:475
  85:     0x7ff61d180373 - std::panic::{{impl}}::call_once<tuple<>,closure-0>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  86:     0x7ff61d171eed - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:348
  87:     0x7ff61d17a0e7 - tokio::time::instant::{{impl}}::gt
  88:     0x7ff61d171cea - std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-0>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:325
  89:     0x7ff61d180c43 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  90:     0x7ff61d1e7716 - std::thread::{{impl}}::spawn_unchecked::{{closure}}<closure-0,tuple<>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\mod.rs:474
  91:     0x7ff61d1a6fae - core::ops::function::FnOnce::call_once<closure-0,tuple<>>
                               at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:233
  92:     0x7ff61d6904da - alloc::boxed::{{impl}}::call_once
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\src\liballoc\boxed.rs:1081
  93:     0x7ff61d6904da - alloc::boxed::{{impl}}::call_once
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\src\liballoc\boxed.rs:1081
  94:     0x7ff61d6904da - std::sys::windows::thread::{{impl}}::new::thread_start
                               at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\sys\windows\thread.rs:56
  95:     0x7ffd0ae26fd4 - BaseThreadInitThunk
  96:     0x7ffd0b19cec1 - RtlUserThreadStart
Fragment '700724208ed0804e59e2f55d1183ccad83d667cf7a2db76184e240ef94a3621f' in block: e21c67ce706eab3eb4d9862aec9cc98779b803b8e753cc2d9db791de6410d2c6 (2.9)

```

**Expected behavior**
no panic

**Additional context**
Error probably occurs when tally vote fragment is send

**Comment by enzoc4** [comment]
is this still happening? or can we close it? I can't reproduce it locally

**Comment by dkijania** [comment]
let me check again.

**Comment by dkijania** [comment]
cannot reproduce either. closing
