### ISSUE TITLE
Panic instead of config error when cors setting is invalid

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2618]
**Describe the bug**
For given configuration with cors settings:

Node shows panic on stderr instead of configuration error:

```
thread 'tokio-runtime-worker' panicked at 'missing scheme', C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\warp-0.2.5\src\filters\cors.rs:616:37
stack backtrace:
0: 0x7ff7dceb9a8e - backtrace::backtrace::trace_unsynchronized
at C:\Users\VssAdministrator.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
1: 0x7ff7dceb9a8e - std::sys_common::backtrace::_print_fmt
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libstd\sys_common\backtrace.rs:78
2: 0x7ff7dceb9a8e - std::sys_common::backtrace::_print::{{impl}}::fmt
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libstd\sys_common\backtrace.rs:59
3: 0x7ff7dced48cc - core::fmt::write
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libcore\fmt\mod.rs:1076
4: 0x7ff7dceb1063 - std::io::Write::write_fmtstd::sys::windows::stdio::Stderr
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libstd\io\mod.rs:1537
5: 0x7ff7dcebcc9b - std::sys_common::backtrace::print
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libstd\sys_common\backtrace.rs:62
6: 0x7ff7dcebcc9b - std::sys_common::backtrace::print
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libstd\sys_common\backtrace.rs:49
7: 0x7ff7dcebcc9b - std::panicking::default_hook::{{closure}}
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libstd\panicking.rs:198
8: 0x7ff7dcebc8e8 - std::panicking::default_hook
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libstd\panicking.rs:217
9: 0x7ff7dcebd46f - std::panicking::rust_panic_with_hook
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libstd\panicking.rs:526
10: 0x7ff7dcebcfef - std::panicking::begin_panic_handler
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libstd\panicking.rs:437
11: 0x7ff7dced2420 - core::panicking::panic_fmt
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libcore\panicking.rs:85
12: 0x7ff7dced21a2 - core::option::expect_failed
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libcore\option.rs:1261
13: 0x7ff7dc666c6b - core::option::Option<str*>::expect<str*>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\option.rs:344
14: 0x7ff7dc611785 - warp::filters::cors::internal::{{impl}}::into_origin
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\warp-0.2.5\src\filters\cors.rs:616
15: 0x7ff7db8f0bca - core::ops::function::FnMut::call_mut<fn(str*) -> headers::common::origin::Origin,tuple<str*>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:154
16: 0x7ff7db8c2ab0 - core::iter::adapters::map_fold::{{closure}}<str*,headers::common::origin::Origin,tuple<>,fn(str*) -> headers::common::origin::Origin,closure-0>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:833
17: 0x7ff7daf6313c - core::iter::traits::iterator::Iterator::fold<alloc::vec::IntoIter<str*>,tuple<>,closure-0>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\traits\iterator.rs:2022
18: 0x7ff7db8d09f8 - core::iter::adapters::{{impl}}::fold<headers::common::origin::Origin,alloc::vec::IntoIter<str*>,fn(str*) -> headers::common::origin::Origin,tuple<>,closure-0>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:873
19: 0x7ff7db8cfde8 - core::iter::adapters::{{impl}}::fold<http::header::value::HeaderValue,core::iter::adapters::Map<alloc::vec::IntoIter<str*>, fn(str*) -> headers::common::origin::Origin>,closure-0,tuple<>,closure-0>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:873
20: 0x7ff7db8cc2e8 - core::iter::adapters::{{impl}}::fold<tuple<http::header::value::HeaderValue, tuple<>>,core::iter::adapters::Map<core::iter::adapters::Map<alloc::vec::IntoIter<str*>, fn(str*) -> headers::common::origin::Origin>, closure-0>,closure-0,tuple<>,closure-0>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:873
21: 0x7ff7db8ace5c - core::iter::traits::iterator::Iterator::for_each<core::iter::adapters::Map<core::iter::adapters::Map<core::iter::adapters::Map<alloc::vec::IntoIter<str*>, fn(str*) -> headers::common::origin::Origin>, closure-0>, closure-0>,closure-0>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\traits\iterator.rs:658
22: 0x7ff7db0cdd6f - hashbrown::map::{{impl}}::extend<http::header::value::HeaderValue,tuple<>,std::collections::hash::map::RandomState,core::iter::adapters::Map<core::iter::adapters::Map<core::iter::adapters::Map<alloc::vec::IntoIter<str*>, fn(str*) -> headers::common::origi
at C:\Users\VssAdministrator.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.6.2\src\map.rs:2578
23: 0x7ff7db231746 - std::collections::hash::map::{{impl}}::extend<http::header::value::HeaderValue,tuple<>,std::collections::hash::map::RandomState,core::iter::adapters::Map<core::iter::adapters::Map<core::iter::adapters::Map<alloc::vec::IntoIter<str*>, fn(str*) -> headers::
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\collections\hash\map.rs:2427
24: 0x7ff7dae7db5a - std::collections::hash::set::{{impl}}::extend<http::header::value::HeaderValue,std::collections::hash::map::RandomState,core::iter::adapters::Map<core::iter::adapters::Map<alloc::vec::IntoIter<str*>, fn(str*) -> headers::common::origin::Origin>, closure-0
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\collections\hash\set.rs:971
25: 0x7ff7db068e9b - warp::filters::cors::Builder::allow_origins<alloc::vec::Vec<str*>>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\warp-0.2.5\src\filters\cors.rs:227
26: 0x7ff7db41ac08 - jormungandr::rest::setup_cors::{{closure}}<warp::filter::and::And<warp::filter::and::And<warp::filters::any::Any, warp::filters::path::Exact<warp::filters::path::internal::Opaquejormungandr::rest::start_rest_server::{{closure}}::__StaticPath>>, warp::fi
at C:\Work\iohk\jormungandr\jormungandr\src\rest\mod.rs:58
27: 0x7ff7db7b3b69 - core::future::from_generator::{{impl}}::poll
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:78
28: 0x7ff7db419df1 - jormungandr::rest::start_rest_server::{{closure}}
at C:\Work\iohk\jormungandr\jormungandr\src\rest\mod.rs:39
29: 0x7ff7db794749 - core::future::from_generator::{{impl}}::poll
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:78
30: 0x7ff7db060c08 - jormungandr::initialize_node::{{closure}}::{{closure}}
at C:\Work\iohk\jormungandr\jormungandr\src\main.rs:547
31: 0x7ff7db7a3669 - core::future::from_generator::{{impl}}::poll
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:78
32: 0x7ff7db65db91 - jormungandr::utils::task::{{impl}}::spawn_future::{{closure}}<closure-0,core::future::from_generator::GenFuture>
at C:\Work\iohk\jormungandr\jormungandr\src\utils\task.rs:100
33: 0x7ff7db7aea79 - core::future::from_generator::{{impl}}::poll
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:78
34: 0x7ff7daf3692f - tokio::runtime::task::core::{{impl}}::poll::{{closure}}<core::future::from_generator::GenFuture,alloc::sync::Arctokio::runtime::thread_pool::worker::Worker>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:173
35: 0x7ff7db3dedca - tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<core::future::from_generator::GenFuture>>::with_mut<tokio::runtime::task::core::Stage<core::future::from_generator::GenFuture>,core::task::poll::Poll<tup
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\loom\std\unsafe_cell.rs:14
36: 0x7ff7daf32489 - tokio::runtime::task::core::Core<core::future::from_generator::GenFuture, alloc::sync::Arctokio::runtime::thread_pool::worker::Worker>::poll<core::future::from_generator::GenFuture,alloc::sync::Arc<tokio::runtime::thread_pool::
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:158
37: 0x7ff7dba700a1 - tokio::runtime::task::harness::{{impl}}::poll::{{closure}}<core::future::from_generator::GenFuture,alloc::sync::Arctokio::runtime::thread_pool::worker::Worker>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:107
38: 0x7ff7db8f6f6a - core::ops::function::FnOnce::call_once<closure-0,tuple<>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:233
39: 0x7ff7db8e91eb - std::panic::{{impl}}::call_once<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,closure-0>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
40: 0x7ff7dbbc0a80 - std::panicking::try::do_call<std::panic::AssertUnwindSafe,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:348
41: 0x7ff7dbbcf127 - std::panicking::try::do_catch<std::panic::AssertUnwindSafe,tuple<>>
42: 0x7ff7dbbb8292 - std::panicking::try<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,std::panic::AssertUnwindSafe>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:325
43: 0x7ff7db8eb20b - std::panic::catch_unwind<std::panic::AssertUnwindSafe,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
44: 0x7ff7dba687eb - tokio::runtime::task::harness::Harness<core::future::from_generator::GenFuture, alloc::sync::Arctokio::runtime::thread_pool::worker::Worker>::poll<core::future::from_generator::GenFuture,alloc::sync::Arc<tokio::runtime::thread
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:89
45: 0x7ff7db0b9de2 - tokio::runtime::task::raw::poll<core::future::from_generator::GenFuture,alloc::sync::Arctokio::runtime::thread_pool::worker::Worker>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:104
46: 0x7ff7dc9a862d - tokio::runtime::task::raw::RawTask::poll
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:66
47: 0x7ff7dc9db107 - tokio::runtime::task::Notified<alloc::sync::Arctokio::runtime::thread_pool::worker::Worker>::run<alloc::sync::Arctokio::runtime::thread_pool::worker::Worker>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\mod.rs:169
48: 0x7ff7dc9d3089 - tokio::runtime::thread_pool::worker::{{impl}}::run_task::{{closure}}
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:353
49: 0x7ff7dc9d8556 - tokio::coop::with_budget::{{closure}}<core::result::Result<alloc::boxed::Boxtokio::runtime::thread_pool::worker::Core, tuple<>>,closure-0>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\coop.rs:127
50: 0x7ff7dc9cec54 - std::thread::local::LocalKey<core::cell::Celltokio::coop::Budget>::try_with<core::cell::Celltokio::coop::Budget,closure-0,core::result::Result<alloc::boxed::Boxtokio::runtime::thread_pool::worker::Core, tuple<>>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:263
51: 0x7ff7dc9ccfad - std::thread::local::LocalKey<core::cell::Celltokio::coop::Budget>::with<core::cell::Celltokio::coop::Budget,closure-0,core::result::Result<alloc::boxed::Boxtokio::runtime::thread_pool::worker::Core, tuple<>>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:239
52: 0x7ff7dc9d2ef9 - tokio::coop::with_budget
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\coop.rs:120
53: 0x7ff7dc9d2ef9 - tokio::coop::budget
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\coop.rs:96
54: 0x7ff7dc9d2ef9 - tokio::runtime::thread_pool::worker::Context::run_task
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:352
55: 0x7ff7dc9d2a83 - tokio::runtime::thread_pool::worker::Context::run
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:324
56: 0x7ff7dc9d290f - tokio::runtime::thread_pool::worker::run::{{closure}}
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:309
57: 0x7ff7dc9d79f9 - tokio::macros::scoped_tls::ScopedKeytokio::runtime::thread_pool::worker::Context::set<tokio::runtime::thread_pool::worker::Context,closure-0,tuple<>>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\macros\scoped_tls.rs:63
58: 0x7ff7dc9d27d3 - tokio::runtime::thread_pool::worker::run
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:306
59: 0x7ff7dc9d26be - tokio::runtime::thread_pool::worker::{{impl}}::launch::{{closure}}
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:285
60: 0x7ff7dc9aa07b - tokio::runtime::blocking::task::{{impl}}::poll<closure-0,tuple<>>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\task.rs:41
61: 0x7ff7dca06b3f - tokio::runtime::task::core::{{impl}}::poll::{{closure}}<tokio::runtime::blocking::task::BlockingTask,tokio::runtime::blocking::schedule::NoopSchedule>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:173
62: 0x7ff7dc9f8a5a - tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask>>::with_mut<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask>,core::task::poll::Po
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\loom\std\unsafe_cell.rs:14
63: 0x7ff7dca0697f - tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask, tokio::runtime::blocking::schedule::NoopSchedule>::poll<tokio::runtime::blocking::task::BlockingTask,tokio::runtime::blocking::schedule::NoopSchedule>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:158
64: 0x7ff7dca25641 - tokio::runtime::task::harness::{{impl}}::poll::{{closure}}<tokio::runtime::blocking::task::BlockingTask,tokio::runtime::blocking::schedule::NoopSchedule>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:107
65: 0x7ff7dc99ebca - core::ops::function::FnOnce::call_once<closure-0,tuple<>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:233
66: 0x7ff7dc9abe0b - std::panic::{{impl}}::call_once<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,closure-0>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
67: 0x7ff7dc9c46f0 - std::panicking::try::do_call<std::panic::AssertUnwindSafe,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:348
68: 0x7ff7dc9cc997 - tokio::time::instant::{{impl}}::gt
69: 0x7ff7dc9c4522 - std::panicking::try<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,std::panic::AssertUnwindSafe>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:325
70: 0x7ff7dc9ac70b - std::panic::catch_unwind<std::panic::AssertUnwindSafe,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
71: 0x7ff7dca2523b - tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask, tokio::runtime::blocking::schedule::NoopSchedule>::poll<tokio::runtime::blocking::task::BlockingTask,tokio::runtime::blocking::schedule::NoopSchedul
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:89
72: 0x7ff7dc9a87c2 - tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask,tokio::runtime::blocking::schedule::NoopSchedule>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:104
73: 0x7ff7dc9a862d - tokio::runtime::task::raw::RawTask::poll
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:66
74: 0x7ff7dc9db187 - tokio::runtime::task::Notifiedtokio::runtime::blocking::schedule::NoopSchedule::runtokio::runtime::blocking::schedule::NoopSchedule
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\mod.rs:169
75: 0x7ff7dc9a99b3 - tokio::runtime::blocking::pool::Inner::run
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\pool.rs:230
76: 0x7ff7dc9a9751 - tokio::runtime::blocking::pool::{{impl}}::spawn_thread::{{closure}}::{{closure}}
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\pool.rs:210
77: 0x7ff7dc99a696 - tokio::runtime::context::enter<closure-0,tuple<>>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\context.rs:72
78: 0x7ff7dc99aeb7 - tokio::runtime::handle::Handle::enter<closure-0,tuple<>>
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\handle.rs:76
79: 0x7ff7dc9a97e3 - tokio::runtime::blocking::pool::{{impl}}::spawn_thread::{{closure}}
at C:\Users\Dariusz.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\pool.rs:209
80: 0x7ff7dc9dd853 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,tuple<>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\sys_common\backtrace.rs:130
81: 0x7ff7dca1aba3 - std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure-0,tuple<>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\mod.rs:475
82: 0x7ff7dc9abde3 - std::panic::{{impl}}::call_once<tuple<>,closure-0>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
83: 0x7ff7dc9c467d - std::panicking::try::do_call<std::panic::AssertUnwindSafe,tuple<>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:348
84: 0x7ff7dc9cc997 - tokio::time::instant::{{impl}}::gt
85: 0x7ff7dc9c440a - std::panicking::try<tuple<>,std::panic::AssertUnwindSafe>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:325
86: 0x7ff7dc9ac6d3 - std::panic::catch_unwind<std::panic::AssertUnwindSafe,tuple<>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
87: 0x7ff7dca1a9d6 - std::thread::{{impl}}::spawn_unchecked::{{closure}}<closure-0,tuple<>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\mod.rs:474
88: 0x7ff7dc99e87e - core::ops::function::FnOnce::call_once<closure-0,tuple<>>
at C:\Users\Dariusz.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:233
89: 0x7ff7dcec1afa - alloc::boxed::{{impl}}::call_once
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\src\liballoc\boxed.rs:1081
90: 0x7ff7dcec1afa - alloc::boxed::{{impl}}::call_once
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\src\liballoc\boxed.rs:1081
91: 0x7ff7dcec1afa - std::sys::windows::thread::{{impl}}::new::thread_start
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd/src\libstd\sys\windows\thread.rs:56
92: 0x7ffc19a26fd4 - BaseThreadInitThunk
93: 0x7ffc19ffcec1 - RtlUserThreadStart
```

**Mandatory Information**
1. `jcli --full-version` newest version;
2. `jormungandr --full-version` newest version;

**To Reproduce**
1. Prepare config with rest section like:

```
rest:
  listen: "127.0.0.1:8008"
  cors:
    allowed_origins:
      - domain.com
    max_age_secs: ~
```
2. start node
3.  Observe panic 
**Expected behavior**
A clear error that cors origin is incorrect

**Additional context**

**Comment by eugene-babichenko** [comment]
A known issue https://github.com/input-output-hk/jormungandr/issues/2425
I filed an issue to `warp` back then, but it wasn't fixed yet. If there is no work on the subject, I will try going the "right" way starting with submitting a patch to `warp`.
