### ISSUE TITLE
Node crashes on incorrect private vote cast

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2712]
**Describe the bug**
During test case development i'm able to reproduce node crash when private vote cast is send using jcli.

Error:

```
non-zero status with message(). waiting 1 s and trying again (4 of 5) 
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', chain-deps\chain-vote\src\committee.rs:186:21 
stack backtrace: 
0: 0x7ff6ebef7c3e - backtrace::backtrace::trace_unsynchronized 
at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66 
1: 0x7ff6ebef7c3e - std::sys_common::backtrace::_print_fmt 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\sys_common\backtrace.rs:78 
2: 0x7ff6ebef7c3e - std::sys_common::backtrace::_print::{{impl}}::fmt 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\sys_common\backtrace.rs:59 
3: 0x7ff6ebf12a7c - core::fmt::write 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libcore\fmt\mod.rs:1076 
4: 0x7ff6ebeef213 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr> 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\io\mod.rs:1537 
5: 0x7ff6ebefae4b - std::sys_common::backtrace::_print 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\sys_common\backtrace.rs:62 
6: 0x7ff6ebefae4b - std::sys_common::backtrace::print 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\sys_common\backtrace.rs:49 
7: 0x7ff6ebefae4b - std::panicking::default_hook::{{closure}} 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\panicking.rs:198 
8: 0x7ff6ebefaa98 - std::panicking::default_hook 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\panicking.rs:217 
9: 0x7ff6ebefb61f - std::panicking::rust_panic_with_hook 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\panicking.rs:526 
10: 0x7ff6ebefb19f - std::panicking::begin_panic_handler 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\panicking.rs:437 
11: 0x7ff6ebf105d0 - core::panicking::panic_fmt 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libcore\panicking.rs:85 
12: 0x7ff6ebf10597 - core::panicking::panic_bounds_check 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libcore\panicking.rs:62 
13: 0x7ff6ebd15d8e - chain_vote::committee::ElectionPublicKey::from_participants 
at C:\Work\iohk\jormungandr\chain-deps\chain-vote\src\committee.rs:186 
14: 0x7ff6ebc8aa1c - chain_impl_mockchain::vote::manager::VotePlanManager::vote 
at C:\Work\iohk\jormungandr\chain-deps\chain-impl-mockchain\src\vote\manager.rs:543 
15: 0x7ff6ebca17b6 - chain_impl_mockchain::vote::ledger::{{impl}}::apply_vote::{{closure}} 
at C:\Work\iohk\jormungandr\chain-deps\chain-impl-mockchain\src\vote\ledger.rs:69 
16: 0x7ff6ebcc351f - imhamt::node::reference::update_rec<chain_crypto::digest::DigestOf<chain_crypto::hash::Blake2b256, chain_impl_mockchain::certificate::vote_plan::VotePlan>,chain_impl_mockchain::vote::m
anager::VotePlanManager,closure-0,chain_impl_mockchain::vote::manager:: 
at C:\Work\iohk\jormungandr\chain-deps\imhamt\src\node\reference.rs:464 
17: 0x7ff6ebbe32ab - imhamt::hamt::Hamt<std::collections::hash::map::DefaultHasher, chain_crypto::digest::DigestOf<chain_crypto::hash::Blake2b256, chain_impl_mockchain::certificate::vote_plan::VotePlan>, c
hain_impl_mockchain::vote::manager::VotePlanManager>::update<std::colle 
at C:\Work\iohk\jormungandr\chain-deps\imhamt\src\hamt.rs:135 
18: 0x7ff6ebca4b83 - chain_impl_mockchain::vote::ledger::VotePlanLedger::apply_vote 
at C:\Work\iohk\jormungandr\chain-deps\chain-impl-mockchain\src\vote\ledger.rs:67 
19: 0x7ff6ebb0d8e8 - chain_impl_mockchain::ledger::ledger::Ledger::apply_vote_cast 
at C:\Work\iohk\jormungandr\chain-deps\chain-impl-mockchain\src\ledger\ledger.rs:1097 
20: 0x7ff6ebb0afaf - chain_impl_mockchain::ledger::ledger::Ledger::apply_fragment 
at C:\Work\iohk\jormungandr\chain-deps\chain-impl-mockchain\src\ledger\ledger.rs:922 
21: 0x7ff6ea9ee943 - jormungandr::fragment::selection::{{impl}}::select 
at C:\Work\iohk\jormungandr\jormungandr\src\fragment\selection.rs:77 
22: 0x7ff6eaa0d926 - jormungandr::fragment::pool::Pool::select 
at C:\Work\iohk\jormungandr\jormungandr\src\fragment\pool.rs:99 
23: 0x7ff6eac98dd0 - jormungandr::fragment::process::{{impl}}::start::{{closure}} 
at C:\Work\iohk\jormungandr\jormungandr\src\fragment\process.rs:93 
24: 0x7ff6e9e16079 - core::future::from_generator::{{impl}}::poll<generator-0> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:78 
25: 0x7ff6ea4bce6b - jormungandr::utils::task::{{impl}}::spawn_try_future::{{closure}}<closure-1,core::future::from_generator::GenFuture<generator-0>> 
at C:\Work\iohk\jormungandr\jormungandr\src\utils\task.rs:137 
26: 0x7ff6e9e2ce19 - core::future::from_generator::{{impl}}::poll<generator-0> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:78 
27: 0x7ff6ea49e39f - tokio::runtime::task::core::{{impl}}::poll::{{closure}}<core::future::from_generator::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:173 
28: 0x7ff6ea588dda - tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<core::future::from_generator::GenFuture<generator-0>>>::with_mut<tokio::runtime::task::core::Stage<core::fut
ure::from_generator::GenFuture<generator-0>>,core::task::poll::Poll<tup 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\loom\std\unsafe_cell.rs:14 
29: 0x7ff6ea4997d9 - tokio::runtime::task::core::Core<core::future::from_generator::GenFuture<generator-0>, alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::poll<core::future::from_generator
::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool:: 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:158 
30: 0x7ff6ea240de1 - tokio::runtime::task::harness::{{impl}}::poll::{{closure}}<core::future::from_generator::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:107 
31: 0x7ff6e9f880ca - core::ops::function::FnOnce::call_once<closure-0,tuple<>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:233 
32: 0x7ff6ea697ebb - std::panic::{{impl}}::call_once<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,closure-0> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318 
33: 0x7ff6ea806380 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:348 
34: 0x7ff6ea80f7a7 - std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,tuple<>> 
35: 0x7ff6ea7f49d2 - std::panicking::try<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,std::panic::AssertUnwindSafe<closure-0>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:325 
36: 0x7ff6ea69b36b - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394 
37: 0x7ff6ea21c7db - tokio::runtime::task::harness::Harness<core::future::from_generator::GenFuture<generator-0>, alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::poll<core::future::from_gen
erator::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_ 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:89 
38: 0x7ff6ea1582a2 - tokio::runtime::task::raw::poll<core::future::from_generator::GenFuture<generator-0>,alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:104 
39: 0x7ff6eb9b3f3d - tokio::runtime::task::raw::RawTask::poll 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:66 
40: 0x7ff6eb9dfec7 - tokio::runtime::task::Notified<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>>::run<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\mod.rs:169 
41: 0x7ff6eb9f0812 - tokio::runtime::thread_pool::worker::{{impl}}::run_task::{{closure}} 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:374 
42: 0x7ff6eb9dd216 - tokio::coop::with_budget::{{closure}}<core::result::Result<alloc::boxed::Box<tokio::runtime::thread_pool::worker::Core>, tuple<>>,closure-0> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\coop.rs:127 
43: 0x7ff6eb9eaf44 - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::result::Result<alloc::boxed::Box<tokio::runtime::thr
ead_pool::worker::Core>, tuple<>>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:263 
44: 0x7ff6eb9ea27d - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::result::Result<alloc::boxed::Box<tokio::runtime::thread_
pool::worker::Core>, tuple<>>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:239 
45: 0x7ff6eb9f04e9 - tokio::coop::with_budget 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\coop.rs:120 
46: 0x7ff6eb9f04e9 - tokio::coop::budget 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\coop.rs:96 
47: 0x7ff6eb9f04e9 - tokio::runtime::thread_pool::worker::Context::run_task 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:352 
48: 0x7ff6eb9f0073 - tokio::runtime::thread_pool::worker::Context::run 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:324 
49: 0x7ff6eb9efeff - tokio::runtime::thread_pool::worker::run::{{closure}} 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:309 
50: 0x7ff6eb9dc6c9 - tokio::macros::scoped_tls::ScopedKey<tokio::runtime::thread_pool::worker::Context>::set<tokio::runtime::thread_pool::worker::Context,closure-0,tuple<>> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\macros\scoped_tls.rs:63 
51: 0x7ff6eb9efdc3 - tokio::runtime::thread_pool::worker::run 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:306 
52: 0x7ff6eb9efcae - tokio::runtime::thread_pool::worker::{{impl}}::launch::{{closure}} 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\worker.rs:285 
53: 0x7ff6eb9b598b - tokio::runtime::blocking::task::{{impl}}::poll<closure-0,tuple<>> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\task.rs:41 
54: 0x7ff6eba07f2f - tokio::runtime::task::core::{{impl}}::poll::{{closure}}<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:173 
55: 0x7ff6eb981faa - tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<closure-0>>>::with_mut<tokio::runtime::task::core::Stage<tokio:
:runtime::blocking::task::BlockingTask<closure-0>>,core::task::poll::Po 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\loom\std\unsafe_cell.rs:14 
56: 0x7ff6eba07d6f - tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<closure-0>, tokio::runtime::blocking::schedule::NoopSchedule>::poll<tokio::runtime::blocking::task::Blocki
ngTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\core.rs:158 
57: 0x7ff6eba0b391 - tokio::runtime::task::harness::{{impl}}::poll::{{closure}}<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:107 
58: 0x7ff6eb9aa43a - core::ops::function::FnOnce::call_once<closure-0,tuple<>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:233 
59: 0x7ff6eb9963bb - std::panic::{{impl}}::call_once<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,closure-0> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318 
60: 0x7ff6eb9e1cb0 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:348 
61: 0x7ff6eb9e9f87 - tokio::time::instant::{{impl}}::gt 
62: 0x7ff6eb9e19d2 - std::panicking::try<core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>,std::panic::AssertUnwindSafe<closure-0>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:325 
63: 0x7ff6eb996d0b - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,core::task::poll::Poll<core::result::Result<tuple<>, tokio::runtime::task::error::JoinError>>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394 
64: 0x7ff6eba0af8b - tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<closure-0>, tokio::runtime::blocking::schedule::NoopSchedule>::poll<tokio::runtime::blocking::task::
BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedul 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\harness.rs:89 
65: 0x7ff6eb9b40d2 - tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask<closure-0>,tokio::runtime::blocking::schedule::NoopSchedule> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:104 
66: 0x7ff6eb9b3f3d - tokio::runtime::task::raw::RawTask::poll 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\raw.rs:66 
67: 0x7ff6eb9dff47 - tokio::runtime::task::Notified<tokio::runtime::blocking::schedule::NoopSchedule>::run<tokio::runtime::blocking::schedule::NoopSchedule> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\task\mod.rs:169 
68: 0x7ff6eb9b52c3 - tokio::runtime::blocking::pool::Inner::run 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\pool.rs:230 
69: 0x7ff6eb9b5061 - tokio::runtime::blocking::pool::{{impl}}::spawn_thread::{{closure}}::{{closure}} 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\pool.rs:210 
70: 0x7ff6eb987f66 - tokio::runtime::context::enter<closure-0,tuple<>> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\context.rs:72 
71: 0x7ff6eb988787 - tokio::runtime::handle::Handle::enter<closure-0,tuple<>> 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\handle.rs:76 
72: 0x7ff6eb9b50f3 - tokio::runtime::blocking::pool::{{impl}}::spawn_thread::{{closure}} 
at C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\blocking\pool.rs:209 
73: 0x7ff6eb996a03 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,tuple<>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\sys_common\backtrace.rs:130 
74: 0x7ff6eb9fb0c3 - std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure-0,tuple<>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\mod.rs:475 
75: 0x7ff6eb996393 - std::panic::{{impl}}::call_once<tuple<>,closure-0> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318 
76: 0x7ff6eb9e1d8d - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,tuple<>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:348 
77: 0x7ff6eb9e9f87 - tokio::time::instant::{{impl}}::gt 
78: 0x7ff6eb9e1b8a - std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-0>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:325 
79: 0x7ff6eb996cd3 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,tuple<>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394 
80: 0x7ff6eb9faef6 - std::thread::{{impl}}::spawn_unchecked::{{closure}}<closure-0,tuple<>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\mod.rs:474 
81: 0x7ff6eb9aa11e - core::ops::function::FnOnce::call_once<closure-0,tuple<>> 
at C:\Users\Dariusz\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:233 
82: 0x7ff6ebeffcaa - alloc::boxed::{{impl}}::call_once 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\src\liballoc\boxed.rs:1081 
83: 0x7ff6ebeffcaa - alloc::boxed::{{impl}}::call_once 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\src\liballoc\boxed.rs:1081 
84: 0x7ff6ebeffcaa - std::sys::windows::thread::{{impl}}::new::thread_start 
at /rustc/e51b714db8ff82ac38ea7c6742d6f5480e2e77bd\/src\libstd\sys\windows\thread.rs:56 
85: 0x7ff8993c7034 - BaseThreadInitThunk 
86: 0x7ff89affcec1 - RtlUserThreadStart 
leadership error: fragment selection failedStandard Output: 
Standard Error: failed to make a REST request 
|-> communication with node failed in unexpected way 
|-> error sending request for url (http://127.0.0.1:9954/api/v0/fragment/logs): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error
10061) 
|-> error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061) 
|-> tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061) 
|-> No connection could be made because the target machine actively refused it. (os error 10061) 
```

**Mandatory Information**
1. `jcli --full-version` output: newest master
2. `jormungandr --full-version` output: newest master

**To Reproduce**
1. checkout branch `private vote`
2. run test from jormungandr-integration-tests: `test jormungandr::vit::private::jcli_e2e_flow_private_vote`
3. Node crashes 

**Expected behavior**
no crash
**Additional context**
I could screw up something, but node should not crash anyhow

**Comment by eugene-babichenko** [comment]
Resolved in https://github.com/input-output-hk/chain-libs/pull/487
