### ISSUE TITLE
JCLI Autocompletion Panic on Linux & Windows

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#383]
**Describe the bug**
Following guide -> https://input-output-hk.github.io/jormungandr/quickstart/01_command_line.html#help-and-auto-completion
Command:
`jcli auto-completion bash ${HOME}/.bash_completion.d`
produces error:
(Ubuntu 18.04)
```thread 'main' panicked at 'couldn't create completion file: other os error', /home/piotr/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/parser.rs:131:25
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
(Windows 10 x64)
```
$ bash --version
GNU bash, version 4.3.42(5)-release (x86_64-pc-msys)
```
error:
```
thread 'main' panicked at 'couldn't create completion file: entity not found', C:\Users\Nobody\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.33.0\src\app\parser.rs:131:25
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**To Reproduce**
1. jcli auto-completion bash ${HOME}/.bash_completion.d

**Expected behavior**
no error

**Comment by piotr-iohk** [comment]
For the record - exact error on Ubuntu:
```
thread 'main' panicked at 'couldn't create completion file: entity not found', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/parser.rs:131:25
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by CodeSandwich** [comment]
I have error from the same place but with other message, Ubuntu 19.04:
```
thread 'main' panicked at 'couldn't create completion file: other os error', /home/zuczek/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.0/src/app/parser.rs:131:25
```

**Comment by CodeSandwich** [comment]
This is and isn't a bug. For case when output does not exist here's a PR with a fix. For case when output is an existing file, this is not a bug, JCLI explicitly asks for an output **directory**.
