### ISSUE TITLE
[Leadership task] End of the epoch: time should always be in the future 

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#385]
**Describe the bug**
When starting node using below files.

[genesis.yaml.txt](https://github.com/input-output-hk/jormungandr/files/3236314/genesis.yaml.txt)
[node.config.txt](https://github.com/input-output-hk/jormungandr/files/3236315/node.config.txt)
[node.secret.txt](https://github.com/input-output-hk/jormungandr/files/3236316/node.secret.txt)

an error is produced:

```
λ jormungandr.exe --secret node.secret --genesis-block block0.bin --config node.config
May 30 11:21:53.807 INFO storing blockchain in memory
May 30 11:21May:53 .85930 11:21: 53.861WARN  no gRPC peers specified, skipping bootstrapINFO
 starting task: transaction
May 30 11:21:53.876 INFO starting task: client-query
May 30 11:21:53.883 INFO starting task: network
May 30 11:21:53.890 INFO our node id: 240579538935935991391069731868055862579
May 30 11:21:53.896 INFO adding P2P Topology module: trusted-peers
May 30 11:21:53.903 INFO start listening and accepting gRPC connections on 127.0.0.1:8606
May 30 11:21:53.910 INFO preparing, task: leadership
May 30 11:21:53.922 INFO starting, task: leadership
May 30 11:21:53.933 INFO starting, task: End Of Epoch Reminder, task: leadership
May 30 11:21:53.946 DEBG scheduling end of epoch, expected_at: SystemTime { intervals: 132036817240000000 }, epoch: 111814, task: End Of Epoch Reminder, task: leadership
May 30 11:21:53.963 DEBG ignoring past events..., epoch_slot: 0, epoch: 111814, task: Leader Task, task: leadership
May 30 11:21:53.980 DEBG ignoring past events..., epoch_slot: 1, epoch: 111814, task: Leader Task, task: leadership
May 30 11:21:53.998 DEBG ignoring past events..., epoch_slot: 2, epoch: 111814, task: Leader Task, task: leadership
May 30 11:21:54.070 DEBG ignoring past events..., epoch_slot: 3, epoch: 111814, task: Leader Task, task: leadership
May 30 11:21:54.088 DEBG loading P2P local topology view []
May 30 11:21:54.095 DEBG not a leader at this time, epoch_slot: 4, epoch: 111814, task: Leader Task, task: leadership May 30 11:22:03.891 DEBG loading P2P local topology view []
May thread '30leadership0 ' panicked at '11time should always be in the future: SystemTimeError(8385975.0012803s):', 2s2rc\libcore\result.rs::09974:.500
1note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
 **INFO End of epoch, epoch: 111814, task: End Of Epoch Reminder, task: leadership
thread 'leadership0' panicked at 'assertion failed: epoch_position.epoch.0 <= task_parameters.epoch', src\leadership\task.rs:131:5**
```

This issue is observed at least on 3 environments (two different Windows 10 x64, Ubuntu 18.04)

**To Reproduce**
1. With input genesis.yaml create block using 
`jcli genesis encode --input genesis.yaml --output block0.bin`
2. start node:
` jormungandr.exe --secret node.secret --genesis-block block0.bin --config node.config`

**Expected behavior**
No error in logs

**Comment by piotr-iohk** [comment]
The issue can be also reproduced when starting a shelley node with small `slots_per_epoch` value in `genesis.yaml`, e.g.:

```
  slots_per_epoch: 10
  slot_duration: 1
  epoch_stability_depth: 10
```
Then if there is no slot leader selected for a given slot there is a _crash_:
```
Jun 07 13:51:49.001 INFO End of epoch, epoch: 3, sub_task: End Of Epoch Reminder, task: leadership
Jun 07 13:52:19.003 INFO End of epoch, epoch: 4, sub_task: End Of Epoch Reminder, task: leadershipthread 'leadership0
' panicked at 'time should always be in the future: SystemTimeError(3.683805ms)', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
