### ISSUE TITLE
Panic on futuristic timestamp in genesis block

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/jormungandr#563]
**Describe the bug**
Jormungandr panicks just after start on certain Windows machines

**To Reproduce**
seen on Windows 2019 and 10.1803
using bootstrap.ps1 which works on a Win2012 server to create all config files

after start (with `RUST_BACKTRACE=1`)

```
D:\jormungandr>jormungandr.exe --genesis-block config\block-0.bin --config config\config.yaml --secret secret\poolsecret1.yaml
Jun 23 23:06:11.023 INFO storing blockchain in '"D:/storage/blocks.sqlite"', task: init
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:345:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: BaseThreadInitThunk
  13: RtlUserThreadStart
```

**Expected behavior**
Show what's wrong or run as expected

**Comment by mzabaluev** [comment]
Obviously one of the `unwrap`s still present in our code.
Would it be possible for you to build jormungandr from source with `cargo build` and run it with `cargo run --bin jormungandr -- --genesis-block ...`? Please also set the environment variable `RUST_BACKTRACE=1`.

**Comment by gufmar** [comment]
ok, done

```
Jun 24 20:35thread ':main33' panicked at '.called `Option::unwrap()` on a `None` value470', src\libcore\option.rs :345DEBG:21
parsing block0 from file path `"config\\block-0.bin"', task: init
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:381
   8: std::panicking::rust_begin_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:308
   9: core::panicking::panic_fmt
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libcore\panicking.rs:85
  10: core::panicking::panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libcore\panicking.rs:49
  11: core::option::Option<chain_time::timeframe::Slot>::unwrap<chain_time::timeframe::Slot>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\macros.rs:12
  12: jormungandr::blockchain::chain::Blockchain::initial
             at C:\Users\Administrator\Documents\gitProjects\jormungandr\jormungandr\src\blockchain\chain.rs:179
  13: jormungandr::start_up::load_blockchain
             at C:\Users\Administrator\Documents\gitProjects\jormungandr\jormungandr\src\start_up\mod.rs:92
  14: jormungandr::bootstrap
             at C:\Users\Administrator\Documents\gitProjects\jormungandr\jormungandr\src\main.rs:257
  15: jormungandr::start
             at C:\Users\Administrator\Documents\gitProjects\jormungandr\jormungandr\src\main.rs:92
  16: jormungandr::main
             at C:\Users\Administrator\Documents\gitProjects\jormungandr\jormungandr\src\main.rs:304
  17: std::rt::lang_start::{{closure}}<()>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\rt.rs:64
  18: std::rt::lang_start_internal::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:49
  19: std::panicking::try::do_call<closure,i32>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:293
  20: panic_unwind::__rust_maybe_catch_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libpanic_unwind\lib.rs:87
  21: std::panicking::try
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:272
  22: std::panic::catch_unwind
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panic.rs:388
  23: std::rt::lang_start_internal
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:48
  24: std::rt::lang_start<()>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\rt.rs:64
  25: main
  26: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  27: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  28: BaseThreadInitThunk
  29: RtlUserThreadStart
```

**Comment by vincenthz** [comment]
so that's timeframe issue at :
1. `core::option::Option<chain_time::timeframe::Slot>::unwrap<chain_time::timeframe::Slot>`
2. `jormungandr::blockchain::chain::Blockchain::initial jormungandr\src\blockchain\chain.rs:179`

**Comment by vincenthz** [comment]
This code:
```
        let slot = self
            .time_frame
            .slot_at(&std::time::SystemTime::now())
            .unwrap();
```

**Comment by gufmar** [comment]
Interesting: It might have to do because of `$BLOCK0_DATE=[int][double]::Parse((Get-Date -UFormat %s))`in the script returns a timestamp value for GMT timezone, while the computers on which I noted this issue are in GMT+2
So the genesis.yaml contains a timestamp 2h in the future which isn't a valid value.

Waiting for two hours makes the config work, which ofc is not the solution.
I'm going to provide a slight fix for the bootstrap.ps1 script, to make it timezone independent.
But may useful to catch this case and tell the sysop to not use futuristic values.
