### ISSUE TITLE
Database error after abrupt node restart

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#676]
**To Reproduce**
1. Start jormungandr in leader mode
2. Make transaction from utxo to account and utxo
3. Shutdown node (kill jormungandr process)
4. Start node with the same command as previously
5. Node is not started and in log we can find: 

```
{"msg":"restoring state at tip 6b1696159fde57760947ee2912c3571b7c55da4a67b4eaf43f68e2bf477c2644","level":"INFO","ts":"2019-08-01T07:26:18.644243399+00:00","task":"bootstrap"}
{"msg":"restoring state from block0 a260e3bec6df5b2782a5c5fa3f1bfbb7147ff2b770797f80837531d63e4207fc","level":"INFO","ts":"2019-08-01T07:26:18.644329460+00:00","task":"bootstrap"}
{"msg":"no gRPC peers specified, skipping bootstrap","level":"WARN","ts":"2019-08-01T07:26:18.644707186+00:00","task":"bootstrap"}
{"msg":"starting task","level":"INFO","ts":"2019-08-01T07:26:18.645111569+00:00","task":"client-query"}
{"msg":"starting task","level":"INFO","ts":"2019-08-01T07:26:18.645203778+00:00","task":"network"}
{"msg":"our node id: 188816294997246603332358673140835087011","level":"INFO","ts":"2019-08-01T07:26:18.645268389+00:00","task":"network"}
{"msg":"adding P2P Topology module: trusted-peers","level":"INFO","ts":"2019-08-01T07:26:18.645319067+00:00","task":"network"}
{"msg":"start listening and accepting gRPC connections on 127.0.0.1:6292","level":"INFO","ts":"2019-08-01T07:26:18.645371710+00:00","task":"network"}
{"msg":"preparing","level":"INFO","ts":"2019-08-01T07:26:18.645431910+00:00","task":"leadership"}
{"msg":"starting","level":"INFO","ts":"2019-08-01T07:26:18.645482630+00:00","task":"leadership"}
{"msg":"starting","level":"INFO","ts":"2019-08-01T07:26:18.645539652+00:00","sub_task":"End Of Epoch Reminder","task":"leadership"}
{"msg":"Leader scheduled event","level":"INFO","ts":"2019-08-01T07:26:19.002035844+00:00","sub_task":"Leader Task","task":"leadership","scheduled_at_date":"104592.39","scheduled at_time":"SystemTime { tv_sec: 1564644379, tv_nsec: 0 }"}
thread 'block0' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: ConstraintViolation, extended_code: 1555 }, Some("UNIQUE constraint failed: Blocks.hash"))', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
{"msg":"Leader scheduled event","level":"INFO","ts":"2019-08-01T07:26:20.001391702+00:00","sub_task":"Leader Task","task":"leadership","scheduled_at_date":"104592.40","scheduled at_time":"SystemTime { tv_sec: 1564644380, tv_nsec: 0 }"}
thread 'leadership0' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError("...")', src/libcore/result.rs:999:5
thread 'arbiter:738f7689-7db6-4c65-9c04-cea7d2603912:actix-net-worker-0' panicked at 'BlockchainR lock is poisoned: poisoned lock: another task failed inside', jormungandr/src/blockchain/chain.rs:56:25
thread 'arbiter:4fe967af-7283-4895-a055-3cfcf618ffe0:actix-net-worker-0' panicked at 'BlockchainR lock is poisoned: poisoned lock: another task failed inside', jormungandr/src/blockchain/chain.rs:56:25
thread 'arbiter:0b506faf-5275-4f55-9aee-a80e72eaea0e:actix-net-worker-0' panicked at 'BlockchainR lock is poisoned: poisoned lock: another task failed inside', jormungandr/src/blockchain/chain.rs:56:25', jormungandr-integration-tests/src/common/jormungandr/starter.rs:104:13
```

**Expected behavior**
Node start sucessfully

**Additional context**
See branch: `recovery_test` and test: `node_restart`

**Comment by NicolasDP** [comment]
please, retry on recent commit on `master`.

**Comment by dkijania** [comment]
After rebase, test is green now. Thanks
