### ISSUE TITLE
thread 'client-query' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/jormungandr#864]
**Describe the bug**
```
Sep 30 09:55:44.431 INFO incoming P2P connection on 172.31.32.144:3000, peer_addr: 172.105.197.118:55698, task: network
Sep 30 09:55:50.272 WARN block solicitation from 17341369084273281157 failed: PropagateError { kind: StreamOverflow, item: [Hash(Blake2b256(0x8c0adeaa00f1f78064d52aeac39f36d657cbcd51fefd34e66b546976be3f3916))] }, task: network
Sep 30 09:55:53.771 INFO block subscription stream failure: Error { code: Unknown, source: Status { code: Unknown, message: "h2 protocol error: broken pipe" } }, sub_task: server, task: network
Sep 30 09:55:53.771 INFO gossip subscription stream failure: Error { code: Unknown, source: Status { code: Unknown, message: "h2 protocol error: broken pipe" } }, sub_task: server, task: network
Sep 30 09:55:53.771 INFO fragment subscription stream failure: Error { code: Unknown, source: Status { code: Unknown, message: "h2 protocol error: broken pipe" } }, sub_task: server, task: network
Sep 30 09:55:54.431 INFO incoming P2P connection on 172.31.32.144:3000, peer_addr: 172.105.197.118:55732, task: network
Sep 30 09:55:57.539 INFO incoming P2P connection on 172.31.32.144:3000, peer_addr: 84.237.246.250:42188, task: network
thread 'client-query' panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")', src/libcore/result.rs:999:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: jormungandr::client::handle_pull_blocks_to_tip
   8: jormungandr::intercom::do_stream_reply
   9: jormungandr::client::handle_input
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 30 09:55:59.924 INFO incoming P2P connection on 172.31.32.144:3000, peer_addr: 84.237.246.250:42204, task: network
Sep 30 09:56:02.383 WARN GetBlocks request (solicitation) failed: Error { code: Canceled, source: Status { code: Cancelled, message: "h2 protocol error: protocol error: stream no longer needed" } }, node_id: 1007204115824491648, peer_add>
Sep 30 09:56:02.388 WARN GetBlocks request (solicitation) failed: Error { code: Canceled, source: Status { code: Cancelled, message: "h2 protocol error: protocol error: stream no longer needed" } }, node_id: 16729047502099380808, peer_ad>
thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: <jormungandr::network::service::NodeService as network_core::server::block::BlockService>::get_blocks
   8: <network_grpc::service::NodeService<T> as network_grpc::gen::node::server::Node>::get_blocks
   9: <tower_grpc::generic::server::server_streaming::Inner<T,S> as futures::future::Future>::poll
  10: <tower_grpc::generic::server::streaming::ResponseFuture<T,E> as futures::future::Future>::poll
  11: <network_grpc::gen::node::server::node::ResponseFuture<T> as futures::future::Future>::poll
  12: <hyper::proto::h2::server::H2Stream<F,B> as futures::future::Future>::poll
  13: futures::task_impl::std::set
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: tokio_threadpool::task::Task::run
  17: tokio_threadpool::worker::Worker::run_task
  18: tokio_threadpool::worker::Worker::run
  19: std::thread::local::LocalKey<T>::with
  20: std::thread::local::LocalKey<T>::with
  21: tokio_reactor::with_default
  22: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  23: std::thread::local::LocalKey<T>::with
  24: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
After that the node stop responding (would be better if it crashed so that it could have been restarted automatically).

**Mandatory Information**
 `jormungandr --full-version` output;
`jormungandr 0.5.2 (, release, linux [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]`

**Comment by dkijania** [comment]
duplicates #813

**Comment by mzabaluev** [comment]
> duplicates #813

Not really.
This panic is due to an unwrap in `ReplyStreamHandle`, which can occur in the wild when the response stream is cancelled by the client.
