### ISSUE TITLE
Backtrace found on faucet jormungandr node

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/jormungandr#868]
**Describe the bug**
backtrace found in faucet logs on 0.5.4 version. Note that this is the jormungandr logs with no secrets, so essentially it's just running as a normal node, nothing special about faucet compared to other rendezvous nodes.
```
Sep 30 18:22:38.452 INFO peer responded with different node id: 401510887185635334, node_id: 401510887185635334, peer_addr: 138.68.122.238:3000, task: network
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: <jormungandr::network::service::NodeService as network_core::server::block::BlockService>::pull_blocks_to_tip
   8: <network_grpc::service::NodeService<T> as network_grpc::gen::node::server::Node>::pull_blocks_to_tip
   9: <tower_grpc::generic::server::server_streaming::Inner<T,S> as futures::future::Future>::poll
  10: <tower_grpc::generic::server::streaming::ResponseFuture<T,E> as futures::future::Future>::poll
  11: <network_grpc::gen::node::server::node::ResponseFuture<T> as futures::future::Future>::poll
  12: <hyper::proto::h2::server::H2Stream<F,B> as futures::future::Future>::poll
  13: futures::task_impl::std::set
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: tokio_threadpool::task::Task::run
  17: tokio_threadpool::worker::Worker::run_task
  18: tokio_threadpool::worker::Worker::run
  19: std::thread::local::LocalKey<T>::with
  20: std::thread::local::LocalKey<T>::with
  21: tokio_reactor::with_default
  22: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  23: std::thread::local::LocalKey<T>::with
  24: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: <jormungandr::network::service::NodeService as network_core::server::block::BlockService>::pull_blocks_to_tip
   8: <network_grpc::service::NodeService<T> as network_grpc::gen::node::server::Node>::pull_blocks_to_tip
   9: <tower_grpc::generic::server::server_streaming::Inner<T,S> as futures::future::Future>::poll
  10: <tower_grpc::generic::server::streaming::ResponseFuture<T,E> as futures::future::Future>::poll
  11: <network_grpc::gen::node::server::node::ResponseFuture<T> as futures::future::Future>::poll
  12: <hyper::proto::h2::server::H2Stream<F,B> as futures::future::Future>::poll
  13: futures::task_impl::std::set
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: tokio_threadpool::task::Task::run
  17: tokio_threadpool::worker::Worker::run_task
  18: tokio_threadpool::worker::Worker::run
  19: std::thread::local::LocalKey<T>::with
  20: std::thread::local::LocalKey<T>::with
  21: tokio_reactor::with_default
  22: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  23: std::thread::local::LocalKey<T>::with
  24: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 30 18:22:38.458 INFO peer responded with different node id: 401510887185635334, node_id: 401510887185635334, peer_addr: 138.68.122.238:3000, task: network
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: <jormungandr::network::service::NodeService as network_core::server::block::BlockService>::pull_blocks_to_tip
   8: <network_grpc::service::NodeService<T> as network_grpc::gen::node::server::Node>::pull_blocks_to_tip
   9: <tower_grpc::generic::server::server_streaming::Inner<T,S> as futures::future::Future>::poll
  10: <tower_grpc::generic::server::streaming::ResponseFuture<T,E> as futures::future::Future>::poll
  11: <network_grpc::gen::node::server::node::ResponseFuture<T> as futures::future::Future>::poll
  12: <hyper::proto::h2::server::H2Stream<F,B> as futures::future::Future>::poll
  13: futures::task_impl::std::set
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: tokio_threadpool::task::Task::run
  17: tokio_threadpool::worker::Worker::run_task
  18: tokio_threadpool::worker::Worker::run
  19: std::thread::local::LocalKey<T>::with
  20: std::thread::local::LocalKey<T>::with
  21: tokio_reactor::with_default
  22: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  23: std::thread::local::LocalKey<T>::with
  24: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 30 18:22:38.464 INFO peer responded with different node id: 401510887185635334, node_id: 401510887185635334, peer_addr: 138.68.122.238:3000, task: network
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: <jormungandr::network::service::NodeService as network_core::server::block::BlockService>::pull_blocks_to_tip
   8: <network_grpc::service::NodeService<T> as network_grpc::gen::node::server::Node>::pull_blocks_to_tip
   9: <tower_grpc::generic::server::server_streaming::Inner<T,S> as futures::future::Future>::poll
  10: <tower_grpc::generic::server::streaming::ResponseFuture<T,E> as futures::future::Future>::poll
  11: <network_grpc::gen::node::server::node::ResponseFuture<T> as futures::future::Future>::poll
  12: <hyper::proto::h2::server::H2Stream<F,B> as futures::future::Future>::poll
  13: futures::task_impl::std::set
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: tokio_threadpool::task::Task::run
  17: tokio_threadpool::worker::Worker::run_task
  18: tokio_threadpool::worker::Worker::run
  19: std::thread::local::LocalKey<T>::with
  20: std::thread::local::LocalKey<T>::with
  21: tokio_reactor::with_default
  22: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  23: std::thread::local::LocalKey<T>::with
  24: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: <jormungandr::network::service::NodeService as network_core::server::block::BlockService>::pull_blocks_to_tip
   8: <network_grpc::service::NodeService<T> as network_grpc::gen::node::server::Node>::pull_blocks_to_tip
   9: <tower_grpc::generic::server::server_streaming::Inner<T,S> as futures::future::Future>::poll
  10: <tower_grpc::generic::server::streaming::ResponseFuture<T,E> as futures::future::Future>::poll
  11: <network_grpc::gen::node::server::node::ResponseFuture<T> as futures::future::Future>::poll
  12: <hyper::proto::h2::server::H2Stream<F,B> as futures::future::Future>::poll
  13: futures::task_impl::std::set
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: tokio_threadpool::task::Task::run
  17: tokio_threadpool::worker::Worker::run_task
  18: tokio_threadpool::worker::Worker::run
  19: std::thread::local::LocalKey<T>::with
  20: std::thread::local::LocalKey<T>::with
  21: tokio_reactor::with_default
  22: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  23: std::thread::local::LocalKey<T>::with
  24: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: <jormungandr::network::service::NodeService as network_core::server::block::BlockService>::pull_blocks_to_tip
   8: <network_grpc::service::NodeService<T> as network_grpc::gen::node::server::Node>::pull_blocks_to_tip
   9: <tower_grpc::generic::server::server_streaming::Inner<T,S> as futures::future::Future>::poll
  10: <tower_grpc::generic::server::streaming::ResponseFuture<T,E> as futures::future::Future>::poll
  11: <network_grpc::gen::node::server::node::ResponseFuture<T> as futures::future::Future>::poll
  12: <hyper::proto::h2::server::H2Stream<F,B> as futures::future::Future>::poll
  13: futures::task_impl::std::set
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: tokio_threadpool::task::Task::run
  17: tokio_threadpool::worker::Worker::run_task
  18: tokio_threadpool::worker::Worker::run
  19: std::thread::local::LocalKey<T>::with
  20: std::thread::local::LocalKey<T>::with
  21: tokio_reactor::with_default
  22: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  23: std::thread::local::LocalKey<T>::with
  24: std::thread::local::LocalKey<T>::with
```
**Mandatory Information**
1. `jcli --full-version` output;
2. `jormungandr --full-version` output;

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by dkijania** [comment]
duplicated #813

**Comment by NicolasDP** [comment]
closing because duplicate to other issues
