### ISSUE TITLE
Jormungandr 0.6.1 // windows10 // public ip // from binaries : Thread Panicked Error

### ISSUE THREAD

**Issue by cardanolondon** [input-output-hk/jormungandr#962]
**Describe the bug**
When I load the node for the first time with the `--secret node_secret.yaml` command added to the normal load command on PowerShell
`PS C:\jormungandr> ./jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --secret node_secret.yaml`

**Mandatory Information**
1. `jcli --full-version` output; jormungandr-v0.6.1-x86_64-pc-windows-msvc.zip
2. `jormungandr --full-version` output; jormungandr-v0.6.1-x86_64-pc-windows-msvc.zip

**To Reproduce**
https://iohk.zendesk.com/hc/en-us/categories/360002383814-Shelley-Networked-Testnet

Follow all instructions for windows10 and work from binaries until a stable version of jormungandr is running.

Then, Go To:
https://iohk.zendesk.com/hc/en-us/articles/360036958953-How-to-create-a-Stake-Pool-using-a-script-Windows-

Use scripts from here:

https://github.com/input-output-hk/shelley-testnet/tree/master/scripts

Run `createStakePool.sh` and `send-certificate.sh`

Go To
https://input-output-hk.github.io/jormungandr/quickstart/05_leader_candidate.html

Create `node_secret.yaml` 

2. Click on:
Load PowerShell,
Type and enter
`cd c:/jormungandr`
Type and enter
`C:\jormungandr> ./jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --secret node_secret.yaml`

```
Oct 15 23:26:53.638 INFO Starting jormungandr 0.6.1 (HEAD-a0de8d47, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Oct 15 23:26:53.653 INFO storing blockchain in '"/jormungandr/nodedata\\blocks.sqlite"', task: init
Oct 15 23:28:39.285 INFO connecting to bootstrap peer 3.115.194.22:3000, peer_addr: 3.115.194.22:3000, task: bootstrap
Oct 15 23:28:40.981 WARN Unable to reach peer for initial bootstrap, reason: HTTP/2.0 connection error, peer_addr: 3.115.194.22:3000, task: bootstrap
Oct 15 23:28:41.006 INFO connecting to bootstrap peer 13.52.208.132:3000, peer_addr: 13.52.208.132:3000, task: bootstrap
Oct 15 23:28:42.432 WARN Unable to reach peer for initial bootstrap, reason: HTTP/2.0 connection error, peer_addr: 13.52.208.132:3000, task: bootstrap
Oct 15 23:28:42.451 INFO connecting to bootstrap peer 52.28.134.8:3000, peer_addr: 52.28.134.8:3000, task: bootstrap
Oct 15 23:28:42.469 WARN with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 52.28.134.8:3000, task: bootstrap
Oct 15 23:28:42.504 INFO connecting to bootstrap peer 52.57.214.174:3000, peer_addr: 52.57.214.174:3000, task: bootstrap
Oct 15 23:28:42.523 WARN with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 52.57.214.174:3000, task: bootstrap
Oct 15 23:28:42.533 INFO connecting to bootstrap peer 54.153.19.202:3000, peer_addr: 54.153.19.202:3000, task: bootstrap
Oct 15 23:28:42.807 WARN with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 54.153.19.202:3000, task: bootstrap
Oct 15 23:28:42.821 INFO connecting to bootstrap peer 13.113.10.64:3000, peer_addr: 13.113.10.64:3000, task: bootstrap
Oct 15 23:28:43.280 WARN with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 13.113.10.64:3000, task: bootstrap
Oct 15 23:28:43.294 INFO connecting to bootstrap peer 3.120.96.93:3000, peer_addr: 3.120.96.93:3000, task: bootstrap
Oct 15 23:28:43.329 WARN with initial bootstrap, reason: bootstrap pull stream failed, peer_addr: 3.120.96.93:3000, task: bootstrap
Oct 15 23:28:43.340 INFO adding P2P Topology module: trusted-peers, task: network
Oct 15 23:28:43.350 INFO start listening and accepting gRPC connections on 0.0.0.0:6100, task: network
Oct 15 23:28:43.356 INFO starting task, task: client-query
Oct 15 23:28:43.365 INFO connecting to initial gossip peer, peer_addr: 52.57.214.174:3000, task: network
Oct 15 23:28:43.376 INFO connecting to initial gossip peer, peer_addr: 3.120.96.93:3000, task: network
Oct 15 23:28:43.386 INFO connecting to initial gossip peer, peer_addr: 13.52.208.132:3000, task: network
Oct 15 23:28:43.392 INFO connecting to initial gossip peer, peer_addr: 52.28.134.8:3000, task: network
Oct 15 23:28:43.399 INFO Starting 1 workers, scope: global
Oct 15 23:28:43.407 INFO Starting server on 127.0.0.1:8443, scope: global
Oct 15 23:28:43.743 INFO incoming P2P connection on 193.105.188.10:6100, peer_addr: 78.46.178.198:55874, task: network
thread 'block0' panicked at 'not yet implemented: method to load a Ref from the storage is not yet there', jormungandr\src\blockchain\chain.rs:259:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
not yet implemented: method to load a Ref from the storage is not yet therethread '
leadership1
```

```
thread 'block0' panicked at 'not yet implemented: method to load a Ref from the storage is not yet there', jormungandr\src\blockchain\chain.rs:259:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
not yet implemented: method to load a Ref from the storage is not yet therethread '
leadership1
```
**Expected behavior**

Node to sync and then partake in generating blocks once the next slot leaders are selected

**Additional context**

**Comment by cardanolondon** [comment]
Deleted the blockchain data files and it's now working!!!
